/**
 * CampaignsPage — GTM Roadmap-first campaign management.
 *
 * Primary view: AI-generated GTM Roadmap (from Campaign Strategist agent)
 * rendered as an interactive React Flow canvas.
 *
 * Secondary: Manual campaign creation wizard (retained for user-added campaigns).
 *
 * ALL roadmap content is generated by agents — this page only VISUALIZES
 * and enables APPROVAL / EDITING / LAUNCHING.
 */

import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles, RefreshCw, CheckCircle, Plus, Map, List,
  Loader2, ChevronRight, ArrowLeft, Zap, Radio, TrendingUp, Users,
} from 'lucide-react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useCompanyId } from '../context/CompanyContext';
import { roadmapApi, type RoadmapResponse, type RoadmapCampaign } from '../api/roadmap';
import { apiClient } from '../api/client';
import { RoadmapCanvas } from '../components/roadmap/RoadmapCanvas';
import { CampaignDetailPanel } from '../components/roadmap/CampaignDetailPanel';

type ViewMode = 'canvas' | 'list';

// ============================================================================
// Campaign Wizard Types & Constants (retained for manual campaign creation)
// ============================================================================

export interface Campaign {
  id: string;
  company_id: string;
  name: string;
  description?: string;
  objective: string; // 'awareness' | 'lead_gen' | 'conversion' | 'retention'
  status: string;    // 'draft' | 'active' | 'paused' | 'completed'
  target_personas: string[];
  target_industries: string[];
  key_messages: string[];
  value_propositions: string[];
  call_to_action?: string;
  channels: string[];
  email_templates: unknown[];
  linkedin_posts: unknown[];
  budget?: number;
  currency: string;
  start_date?: string;
  end_date?: string;
  created_at: string;
  updated_at?: string;
}

type WizardStep = 1 | 2 | 3;
type Objective = 'lead_gen' | 'awareness' | 'conversion' | 'retention';

const OBJECTIVE_CONFIG: Record<
  Objective,
  { label: string; description: string; color: string; bg: string; border: string; icon: React.ReactNode }
> = {
  lead_gen: {
    label: 'Lead Generation',
    description: 'Attract and convert new prospects into qualified leads',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
    icon: <Zap className="w-5 h-5" />,
  },
  awareness: {
    label: 'Brand Awareness',
    description: 'Increase visibility and recognition in your target market',
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/30',
    icon: <Radio className="w-5 h-5" />,
  },
  conversion: {
    label: 'Conversion',
    description: 'Turn engaged prospects into paying customers',
    color: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    icon: <TrendingUp className="w-5 h-5" />,
  },
  retention: {
    label: 'Customer Retention',
    description: 'Keep existing customers engaged and reduce churn',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    icon: <Users className="w-5 h-5" />,
  },
};

const CHANNEL_OPTIONS: { value: string; label: string }[] = [
  { value: 'email',    label: 'Email' },
  { value: 'linkedin', label: 'LinkedIn' },
  { value: 'events',   label: 'Events' },
  { value: 'referral', label: 'Referral' },
];

// ============================================================================
// Sub-components (Campaign Wizard)
// ============================================================================

function ObjectiveCard({
  objective,
  selected,
  onSelect,
}: {
  objective: Objective;
  selected: boolean;
  onSelect: () => void;
}) {
  const cfg = OBJECTIVE_CONFIG[objective];
  return (
    <motion.button
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      onClick={onSelect}
      className={`w-full text-left glass-card p-4 rounded-xl border-2 transition-all ${
        selected
          ? `${cfg.border} ring-1 ring-current/40`
          : 'border-white/10 hover:border-white/20'
      }`}
    >
      <div className="flex items-start gap-3">
        <div className={`w-10 h-10 rounded-lg ${cfg.bg} flex items-center justify-center flex-shrink-0 ${cfg.color}`}>
          {cfg.icon}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-sm font-semibold text-white">{cfg.label}</span>
            {selected && <CheckCircle className={`w-3.5 h-3.5 flex-shrink-0 ${cfg.color}`} />}
          </div>
          <p className="text-xs text-white/50 leading-relaxed">{cfg.description}</p>
        </div>
      </div>
    </motion.button>
  );
}

// ============================================================================
// Campaign Builder Wizard
// ============================================================================

function CampaignWizard({
  companyId,
  initialStep,
  initialName,
  onClose,
  onSuccess,
}: {
  companyId: string;
  initialStep?: WizardStep;
  initialName?: string;
  onClose: () => void;
  onSuccess: () => void;
}) {
  const [step, setStep] = useState<WizardStep>(initialStep ?? 1);
  const [objective, setObjective] = useState<Objective>('lead_gen');
  const [campaignName, setCampaignName] = useState(initialName ?? '');
  const [description, setDescription] = useState('');
  const [selectedChannels, setSelectedChannels] = useState<string[]>(['email']);
  const [budget, setBudget] = useState('');
  const [launching, setLaunching] = useState(false);
  const [launchError, setLaunchError] = useState<string | null>(null);

  const toggleChannel = (value: string) => {
    setSelectedChannels(prev =>
      prev.includes(value) ? prev.filter(c => c !== value) : [...prev, value],
    );
  };

  const handleLaunch = async () => {
    if (!campaignName.trim()) return;
    setLaunching(true);
    setLaunchError(null);
    try {
      await apiClient.post(`/companies/${companyId}/campaigns`, {
        name: campaignName.trim(),
        objective,
        channels: selectedChannels,
        description: description.trim() || undefined,
        budget: budget ? parseFloat(budget) : undefined,
        currency: 'SGD',
      });
      onSuccess();
    } catch (err) {
      setLaunchError(err instanceof Error ? err.message : 'Failed to create campaign');
      setLaunching(false);
    }
  };

  const canAdvanceStep1 = true; // objective always has a default
  const canAdvanceStep2 = campaignName.trim().length > 0;

  const objCfg = OBJECTIVE_CONFIG[objective];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(8px)' }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 16 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 16 }}
        className="glass-card w-full max-w-lg rounded-2xl border border-white/15 overflow-hidden"
      >
        {/* Wizard header */}
        <div className="px-6 py-4 border-b border-white/10 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-white">New Campaign</h2>
            <p className="text-xs text-white/40 mt-0.5">Step {step} of 3</p>
          </div>
          <div className="flex items-center gap-1.5">
            {([1, 2, 3] as WizardStep[]).map(s => (
              <div
                key={s}
                className={`w-2 h-2 rounded-full transition-colors ${
                  s < step ? 'bg-purple-400' : s === step ? 'bg-purple-500' : 'bg-white/15'
                }`}
              />
            ))}
          </div>
        </div>

        {/* Step content */}
        <div className="px-6 py-5 max-h-[60vh] overflow-y-auto">
          <AnimatePresence mode="wait">
            {/* Step 1: Objective */}
            {step === 1 && (
              <motion.div
                key="step1"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-3"
              >
                <p className="text-sm text-white/60 mb-4">What is the primary goal of this campaign?</p>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  {(Object.keys(OBJECTIVE_CONFIG) as Objective[]).map(obj => (
                    <ObjectiveCard
                      key={obj}
                      objective={obj}
                      selected={objective === obj}
                      onSelect={() => setObjective(obj)}
                    />
                  ))}
                </div>
              </motion.div>
            )}

            {/* Step 2: Details */}
            {step === 2 && (
              <motion.div
                key="step2"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-5"
              >
                <p className="text-sm text-white/60">Give your campaign a name and configure channels.</p>

                {/* Campaign name */}
                <div>
                  <label className="block text-xs font-medium text-white/50 mb-2">
                    Campaign name <span className="text-red-400">*</span>
                  </label>
                  <input
                    type="text"
                    value={campaignName}
                    onChange={e => setCampaignName(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/20 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/30 transition-colors"
                    placeholder="e.g. Q1 Lead Generation Campaign"
                  />
                </div>

                {/* Description */}
                <div>
                  <label className="block text-xs font-medium text-white/50 mb-2">Description (optional)</label>
                  <textarea
                    value={description}
                    onChange={e => setDescription(e.target.value)}
                    rows={3}
                    className="w-full px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/20 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/30 transition-colors resize-none"
                    placeholder="Brief description of the campaign goals..."
                  />
                </div>

                {/* Channels */}
                <div>
                  <label className="block text-xs font-medium text-white/50 mb-2">Channels</label>
                  <div className="grid grid-cols-2 gap-2">
                    {CHANNEL_OPTIONS.map(ch => (
                      <label
                        key={ch.value}
                        className={`flex items-center gap-2.5 px-3 py-2.5 rounded-xl border cursor-pointer transition-colors ${
                          selectedChannels.includes(ch.value)
                            ? 'border-purple-500/40 bg-purple-500/10'
                            : 'border-white/10 hover:border-white/20 bg-white/5'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={selectedChannels.includes(ch.value)}
                          onChange={() => toggleChannel(ch.value)}
                          className="accent-purple-500"
                        />
                        <span className="text-sm text-white/80">{ch.label}</span>
                      </label>
                    ))}
                  </div>
                </div>

                {/* Budget */}
                <div>
                  <label className="block text-xs font-medium text-white/50 mb-2">Budget in SGD (optional)</label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-white/30">SGD</span>
                    <input
                      type="number"
                      min="0"
                      step="100"
                      value={budget}
                      onChange={e => setBudget(e.target.value)}
                      className="w-full pl-12 pr-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/20 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/30 transition-colors"
                      placeholder="0"
                    />
                  </div>
                </div>
              </motion.div>
            )}

            {/* Step 3: Review */}
            {step === 3 && (
              <motion.div
                key="step3"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-4"
              >
                <p className="text-sm text-white/60 mb-2">Review your campaign before launching.</p>

                <div className="glass-card rounded-xl border border-white/10 p-4 space-y-3">
                  {/* Objective */}
                  <div className="flex items-center gap-3">
                    <div className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 ${objCfg.bg} ${objCfg.color}`}>
                      {objCfg.icon}
                    </div>
                    <div>
                      <p className="text-xs text-white/40">Objective</p>
                      <p className="text-sm font-semibold text-white">{objCfg.label}</p>
                    </div>
                  </div>

                  <div className="border-t border-white/5 pt-3 space-y-2">
                    <div className="flex items-start justify-between text-xs gap-3">
                      <span className="text-white/40 flex-shrink-0">Campaign name</span>
                      <span className="text-white font-medium text-right">{campaignName}</span>
                    </div>
                    {description && (
                      <div className="flex items-start justify-between text-xs gap-3">
                        <span className="text-white/40 flex-shrink-0">Description</span>
                        <span className="text-white/70 text-right line-clamp-2">{description}</span>
                      </div>
                    )}
                    <div className="flex items-start justify-between text-xs gap-3">
                      <span className="text-white/40 flex-shrink-0">Channels</span>
                      <span className="text-white font-medium text-right capitalize">
                        {selectedChannels.length > 0 ? selectedChannels.join(', ') : 'None'}
                      </span>
                    </div>
                    {budget && (
                      <div className="flex items-start justify-between text-xs gap-3">
                        <span className="text-white/40 flex-shrink-0">Budget</span>
                        <span className="text-white font-medium">SGD {parseFloat(budget).toLocaleString()}</span>
                      </div>
                    )}
                  </div>
                </div>

                {launchError && (
                  <p className="text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-2">
                    {launchError}
                  </p>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Footer actions */}
        <div className="px-6 py-4 border-t border-white/10 flex items-center justify-between gap-3">
          <button
            onClick={step === 1 ? onClose : () => setStep(prev => (prev - 1) as WizardStep)}
            className="flex items-center gap-1.5 text-xs text-white/50 hover:text-white/80 transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            {step === 1 ? 'Cancel' : 'Back'}
          </button>

          {step < 3 ? (
            <button
              disabled={step === 1 ? !canAdvanceStep1 : !canAdvanceStep2}
              onClick={() => setStep(prev => (prev + 1) as WizardStep)}
              className="flex items-center gap-2 px-5 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-violet-600 text-white text-xs font-semibold hover:from-purple-500 hover:to-violet-500 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Next
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          ) : (
            <button
              disabled={launching}
              onClick={handleLaunch}
              className="flex items-center gap-2 px-5 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-violet-600 text-white text-xs font-semibold hover:from-purple-500 hover:to-violet-500 transition-all disabled:opacity-50"
            >
              {launching ? (
                <>
                  <span className="w-3 h-3 border border-white border-t-transparent rounded-full animate-spin" />
                  Launching...
                </>
              ) : (
                <>
                  <Zap className="w-3.5 h-3.5" />
                  Launch Campaign
                </>
              )}
            </button>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ============================================================================
// Main page — Roadmap-first design
// ============================================================================

export function CampaignsPage() {
  const companyId = useCompanyId();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [roadmapData, setRoadmapData] = useState<RoadmapResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedCampaign, setSelectedCampaign] = useState<RoadmapCampaign | null>(null);
  // Default to list on mobile (Gantt chart requires horizontal space)
  const [viewMode, setViewMode] = useState<ViewMode>(
    typeof window !== 'undefined' && window.innerWidth < 768 ? 'list' : 'canvas'
  );
  const [error, setError] = useState<string | null>(null);

  // Manual campaign wizard state (secondary feature)
  const [showWizard, setShowWizard] = useState(false);
  const [wizardInitialStep, setWizardInitialStep] = useState<WizardStep>(1);
  const [wizardInitialName, setWizardInitialName] = useState<string>('');

  // URLSearchParams: deep-link for manual wizard (signal-triggered or strategy-driven)
  useEffect(() => {
    const signal = searchParams.get('signal');
    const playbook = searchParams.get('playbook');
    const headline = searchParams.get('headline');
    if (signal && playbook === 'signal_triggered') {
      setWizardInitialStep(2);
      setWizardInitialName(headline || 'Signal-Triggered Campaign');
      setShowWizard(true);
    } else if (!signal && headline) {
      setWizardInitialStep(2);
      setWizardInitialName(headline);
      setShowWizard(true);
    }
  }, [searchParams]);

  // Fetch roadmap on mount
  const fetchRoadmap = useCallback(async () => {
    if (!companyId) return;
    setLoading(true);
    setError(null);
    try {
      const data = await roadmapApi.getRoadmap(companyId);
      setRoadmapData(data);
    } catch (err) {
      setError('Failed to load roadmap');
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [companyId]);

  useEffect(() => {
    fetchRoadmap();
  }, [fetchRoadmap]);

  // Poll for roadmap when generating
  useEffect(() => {
    if (!generating) return;
    const interval = setInterval(async () => {
      if (!companyId) return;
      try {
        const data = await roadmapApi.getRoadmap(companyId);
        if (data.has_roadmap) {
          setRoadmapData(data);
          setGenerating(false);
        }
      } catch {
        // Keep polling
      }
    }, 5000);
    return () => clearInterval(interval);
  }, [generating, companyId]);

  // Approve roadmap — changes status to IN_PROGRESS
  const handleApprove = async () => {
    if (!companyId || !roadmapData?.roadmap?.id) return;
    try {
      await roadmapApi.approveRoadmap(companyId, roadmapData.roadmap.id);
      await fetchRoadmap(); // Refresh
    } catch (err) {
      setError('Failed to approve roadmap');
    }
  };

  // Revise roadmap — re-runs Campaign Strategist with latest data
  const handleRevise = async () => {
    if (!companyId || !roadmapData?.roadmap?.id) return;
    setGenerating(true);
    try {
      await roadmapApi.reviseRoadmap(companyId, roadmapData.roadmap.id);
    } catch (err) {
      setError('Failed to start revision');
      setGenerating(false);
    }
  };

  // Select campaign — open detail panel
  const handleSelectCampaign = useCallback((campaignId: string) => {
    if (!roadmapData?.phases) return;
    // Find campaign across all phases
    const allCampaigns = [
      ...(roadmapData.phases.immediate || []),
      ...(roadmapData.phases.short_term || []),
      ...(roadmapData.phases.mid_term || []),
      ...(roadmapData.phases.long_term || []),
    ];
    const campaign = allCampaigns.find((c) => c.id === campaignId);
    setSelectedCampaign(campaign || null);
  }, [roadmapData]);

  // Generate creative — triggers EDM Designer + Graphic Designer agents
  const handleGenerateCreative = useCallback(async (campaignId: string) => {
    if (!companyId) return;
    try {
      await roadmapApi.generateCreative(companyId, campaignId, {
        asset_types: ['edm_html', 'social_image'],
        platforms: ['linkedin', 'email'],
      });
      // Refresh after a delay to pick up generated assets
      setTimeout(fetchRoadmap, 3000);
    } catch (err) {
      console.error('Generate creative failed:', err);
    }
  }, [companyId, fetchRoadmap]);

  // Launch campaign — activates + distributes via Social Publisher agent
  const handleLaunch = useCallback(async (campaignId: string) => {
    if (!companyId) return;
    try {
      await roadmapApi.launchCampaign(companyId, campaignId);
      await fetchRoadmap();
    } catch (err) {
      console.error('Launch failed:', err);
    }
  }, [companyId, fetchRoadmap]);

  // Manual wizard callbacks
  const openFreshWizard = () => {
    setWizardInitialStep(1);
    setWizardInitialName('');
    setShowWizard(true);
  };

  const handleWizardSuccess = () => {
    setShowWizard(false);
    fetchRoadmap(); // Refresh roadmap after manual campaign creation
  };

  if (!companyId) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-white/40">Select a company to view your growth roadmap</p>
      </div>
    );
  }

  // Loading state
  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="w-6 h-6 text-purple-400 animate-spin" />
      </div>
    );
  }

  // No roadmap yet — inform user it is auto-generated as part of the analysis pipeline
  if (!roadmapData?.has_roadmap) {
    return (
      <>
        <div className="flex items-center justify-center h-full px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-lg text-center space-y-6"
          >
            <div className="w-16 h-16 rounded-2xl bg-purple-500/10 flex items-center justify-center mx-auto">
              <Map className="w-8 h-8 text-purple-400" />
            </div>

            {generating ? (
              /* Analysis in progress — roadmap is being built as Step 6 */
              <>
                <div>
                  <h2 className="text-xl font-semibold text-white">Building Your Growth Roadmap</h2>
                  <p className="text-sm text-white/50 mt-2 leading-relaxed">
                    The Campaign Strategist is analysing your market, competitors, and customer
                    profiles to create a phased growth roadmap.
                  </p>
                </div>
                <div className="flex items-center justify-center gap-3 px-6 py-3 rounded-xl bg-purple-500/10">
                  <Loader2 className="w-5 h-5 text-purple-400 animate-spin" />
                  <span className="text-sm text-purple-300">
                    Campaign Strategist is building your roadmap...
                  </span>
                </div>
              </>
            ) : (
              /* No roadmap — direct to Strategy page to approve strategies first */
              <>
                <div>
                  <h2 className="text-xl font-semibold text-white">Campaign Plan</h2>
                  <p className="text-sm text-white/50 mt-2 leading-relaxed">
                    Your campaign plan is generated from approved strategies.
                    Review and approve your strategies first, then generate the campaign plan.
                  </p>
                </div>
                <button
                  onClick={() => navigate('/strategy')}
                  className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-indigo-500/20 text-indigo-300 hover:bg-indigo-500/30 transition-colors font-medium"
                >
                  <Sparkles className="w-5 h-5" />
                  Go to Strategy
                </button>
              </>
            )}

            {error && <p className="text-xs text-red-400">{error}</p>}
          </motion.div>
        </div>

        {/* Manual Campaign Builder Wizard (signal-triggered deep-link) */}
        <AnimatePresence>
          {showWizard && (
            <CampaignWizard
              companyId={companyId}
              initialStep={wizardInitialStep}
              initialName={wizardInitialName}
              onClose={() => setShowWizard(false)}
              onSuccess={handleWizardSuccess}
            />
          )}
        </AnimatePresence>
      </>
    );
  }

  // Roadmap exists — render canvas + controls
  return (
    <>
      <div className="h-full flex flex-col">
        {/* Toolbar */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-white/10 flex-shrink-0">
          <div className="flex items-center gap-3">
            <h1 className="text-lg font-semibold text-white">Campaigns</h1>
            {roadmapData.roadmap?.status === 'proposed' && (
              <span className="px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-400 text-[10px] font-medium">
                Awaiting Approval
              </span>
            )}
            {roadmapData.roadmap?.status === 'in_progress' && (
              <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 text-[10px] font-medium">
                In Progress
              </span>
            )}
          </div>

          <div className="flex items-center gap-2">
            {/* View mode toggle */}
            <div className="flex items-center bg-white/5 rounded-lg p-0.5">
              <button
                onClick={() => setViewMode('canvas')}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                  viewMode === 'canvas' ? 'bg-white/10 text-white' : 'text-white/40 hover:text-white/60'
                }`}
              >
                <Map className="w-3.5 h-3.5 inline mr-1" />
                Canvas
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                  viewMode === 'list' ? 'bg-white/10 text-white' : 'text-white/40 hover:text-white/60'
                }`}
              >
                <List className="w-3.5 h-3.5 inline mr-1" />
                List
              </button>
            </div>

            {/* Approve roadmap */}
            {roadmapData.roadmap?.status === 'proposed' && (
              <button
                onClick={handleApprove}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30 transition-colors text-xs font-medium"
              >
                <CheckCircle className="w-3.5 h-3.5" />
                Approve Roadmap
              </button>
            )}

            {/* Revise with AI */}
            <button
              onClick={handleRevise}
              disabled={generating}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-purple-500/10 text-purple-300 hover:bg-purple-500/20 transition-colors text-xs font-medium disabled:opacity-40"
            >
              {generating ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <RefreshCw className="w-3.5 h-3.5" />
              )}
              {generating ? 'Regenerating...' : 'Revise with AI'}
            </button>

            {/* Manual campaign creation */}
            <button
              onClick={openFreshWizard}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/5 text-white/50 hover:bg-white/10 hover:text-white/70 transition-colors text-xs font-medium"
            >
              <Plus className="w-3.5 h-3.5" />
              Manual
            </button>
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 relative overflow-hidden">
          {viewMode === 'canvas' ? (
            <RoadmapCanvas
              roadmapData={roadmapData}
              onSelectCampaign={handleSelectCampaign}
              onGenerateCreative={handleGenerateCreative}
              onLaunchCampaign={handleLaunch}
            />
          ) : (
            /* List view — simple phased list fallback */
            <div className="overflow-y-auto h-full px-6 py-4 space-y-6">
              {(['immediate', 'short_term', 'mid_term', 'long_term'] as const).map((phase) => {
                const campaigns = roadmapData.phases?.[phase] || [];
                if (campaigns.length === 0) return null;
                const phaseLabels: Record<string, string> = {
                  immediate: 'Immediate (Week 1-2)',
                  short_term: 'Short Term (30-60-90 Days)',
                  mid_term: 'Mid Term (3-6 Months)',
                  long_term: 'Long Term (6-12 Months)',
                };
                return (
                  <div key={phase}>
                    <h3 className="text-sm font-semibold text-white/60 mb-3">{phaseLabels[phase]}</h3>
                    <div className="space-y-2">
                      {campaigns.map((c) => (
                        <motion.button
                          key={c.id}
                          onClick={() => setSelectedCampaign(c)}
                          whileHover={{ x: 2 }}
                          className="w-full text-left p-3 rounded-xl bg-white/5 hover:bg-white/8 border border-white/5 transition-colors"
                        >
                          <div className="flex items-center gap-3">
                            <div className={`w-2 h-2 rounded-full ${
                              c.status === 'completed' ? 'bg-emerald-400' :
                              c.status === 'active' ? 'bg-blue-400' :
                              'bg-white/20'
                            }`} />
                            <div className="flex-1 min-w-0">
                              <p className="text-sm text-white font-medium truncate">{c.name}</p>
                              <p className="text-[10px] text-purple-300/60 truncate">{c.framework_rationale}</p>
                            </div>
                            <div className="flex gap-1">
                              {c.channels.slice(0, 3).map((ch) => (
                                <span key={ch} className="text-[9px] px-1.5 py-0.5 rounded bg-white/5 text-white/30">{ch}</span>
                              ))}
                            </div>
                          </div>
                        </motion.button>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {/* Campaign detail panel */}
          {selectedCampaign && (
            <CampaignDetailPanel
              campaign={selectedCampaign}
              companyId={companyId}
              onClose={() => setSelectedCampaign(null)}
              onGenerateCreative={handleGenerateCreative}
              onLaunch={handleLaunch}
            />
          )}
        </div>
      </div>

      {/* Manual Campaign Builder Wizard */}
      <AnimatePresence>
        {showWizard && (
          <CampaignWizard
            companyId={companyId}
            initialStep={wizardInitialStep}
            initialName={wizardInitialName}
            onClose={() => setShowWizard(false)}
            onSuccess={handleWizardSuccess}
          />
        )}
      </AnimatePresence>
    </>
  );
}

