/**
 * Roadmap API client — calls the GTM Roadmap backend endpoints.
 * All roadmap content is generated by the Campaign Strategist agent.
 */
import { apiClient } from './client';

export interface RoadmapCampaign {
  id: string;
  name: string;
  description?: string;
  objective?: string;
  status: string;
  phase: string;
  priority_rank?: number;
  strategy_track?: string;
  framework_rationale?: string;
  knowledge_source?: string;
  channels: string[];
  content_types_needed: string[];
  estimated_impact?: string;
  recommended_by_ai: boolean;
  budget?: number;
  metrics: Record<string, unknown>;
  created_at?: string;
}

export interface RoadmapData {
  id: string;
  company_id: string;
  title: string;
  executive_summary: string;
  gtm_motion: string;
  status: string;
  planning_horizon_months: number;
  company_diagnosis: Record<string, unknown>;
  frameworks_applied: Array<Record<string, unknown>>;
  knowledge_sources: string[];
  confidence: number;
  created_at?: string;
  approved_at?: string;
}

export interface RoadmapResponse {
  has_roadmap: boolean;
  message?: string;
  roadmap?: RoadmapData;
  phases?: {
    immediate: RoadmapCampaign[];
    short_term: RoadmapCampaign[];
    mid_term: RoadmapCampaign[];
    long_term: RoadmapCampaign[];
    unphased: RoadmapCampaign[];
  };
  summary?: {
    total_campaigns: number;
    active_campaigns: number;
    completed_campaigns: number;
  };
}

export interface CreativeAsset {
  id: string;
  campaign_id: string;
  asset_type: string;
  status: string;
  name: string;
  content_html?: string;
  image_url?: string;
  copy_text?: string;
  call_to_action?: string;
  target_platform?: string;
  impressions: number;
  clicks: number;
  engagements: number;
  created_at: string;
}

export const roadmapApi = {
  getRoadmap: (companyId: string) =>
    apiClient.get<RoadmapResponse>(`/companies/${companyId}/roadmap`),

  generateRoadmap: (companyId: string, opts?: { planning_horizon_months?: number; analysis_id?: string }) =>
    apiClient.post<{ status: string; message: string }>(`/companies/${companyId}/roadmap/generate`, opts || {}),

  approveRoadmap: (companyId: string, roadmapId: string) =>
    apiClient.post<{ status: string }>(`/companies/${companyId}/roadmap/${roadmapId}/approve`, {}),

  reviseRoadmap: (companyId: string, roadmapId: string) =>
    apiClient.post<{ status: string; message: string }>(`/companies/${companyId}/roadmap/${roadmapId}/revise`, {}),

  // Campaign assets (from creative agents)
  getCampaignAssets: (companyId: string, campaignId: string) =>
    apiClient.get<CreativeAsset[]>(`/companies/${companyId}/campaigns/${campaignId}/assets`),

  generateCreative: (companyId: string, campaignId: string, opts: { asset_types: string[]; platforms: string[] }) =>
    apiClient.post<{ status: string }>(`/companies/${companyId}/campaigns/${campaignId}/generate-creative`, opts),

  approveCampaignAsset: (companyId: string, campaignId: string, assetId: string) =>
    apiClient.post<CreativeAsset>(`/companies/${companyId}/campaigns/${campaignId}/assets/${assetId}/approve`, {}),

  launchCampaign: (companyId: string, campaignId: string) =>
    apiClient.post<{ status: string }>(`/companies/${companyId}/campaigns/${campaignId}/launch`, {}),

  // Campaign performance (from monitor agent)
  getCampaignAttribution: (companyId: string, campaignId: string) =>
    apiClient.get<Record<string, unknown>>(`/companies/${companyId}/attribution/campaign/${campaignId}`),
};
