import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Users, Lightbulb, Mail, ExternalLink, Download, TrendingUp, Cpu, Brain, Wrench, Shield, Bot, RefreshCw, Zap, Lock, ArrowRight } from 'lucide-react';
import { AnalysisResult } from '../types';
import { apiClient } from '../api/client';
import { useCompanyId } from '../context/CompanyContext';

interface ResultsPanelProps {
  results: AnalysisResult;
}

export function ResultsPanel({ results }: ResultsPanelProps) {
  const navigate = useNavigate();
  const contextCompanyId = useCompanyId();
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const handleExportReport = async () => {
    // Prefer context (most up-to-date), fall back to sessionStorage for teaser flow
    const companyId = contextCompanyId ?? sessionStorage.getItem('gtm_company_id');
    if (!companyId) {
      setExportError('No company loaded. Run an analysis first.');
      setTimeout(() => setExportError(null), 3000);
      return;
    }
    setIsExporting(true);
    setExportError(null);
    try {
      const blob = await apiClient.getBlob(`/companies/${companyId}/full-report/json`);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gtm-report-${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      setExportError('Export failed. Please try again.');
      setTimeout(() => setExportError(null), 3000);
    } finally {
      setIsExporting(false);
    }
  };

  const handleCopyTemplate = (content: string | undefined, index: number) => {
    if (!content) return;
    navigator.clipboard.writeText(content);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <motion.div
      className="w-96 border-l border-white/10 bg-surface/50 backdrop-blur-xl overflow-y-auto"
      initial={{ x: 100, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      exit={{ x: 100, opacity: 0 }}
      transition={{ type: 'spring', damping: 25 }}
    >
      {/* Header */}
      <div className="sticky top-0 p-4 border-b border-white/10 bg-surface/80 backdrop-blur-xl z-10">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-semibold text-white">Analysis Results</h2>
            <p className="text-xs text-white/50">Generated by 12 AI agents</p>
          </div>
          <button
            className="btn-ghost p-2 disabled:opacity-50"
            onClick={handleExportReport}
            disabled={isExporting}
            title="Export full report as JSON"
          >
            <Download className={`w-4 h-4 ${isExporting ? 'animate-pulse' : ''}`} />
          </button>
        </div>
      </div>

      <div className="p-4 space-y-6">
        {/* Executive Summary Banner */}
        {results.executiveSummary && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm"
          >
            <h3 className="mb-3 text-sm font-semibold uppercase tracking-wider text-purple-400">
              GTM Intelligence Summary
            </h3>
            <p className="text-base leading-relaxed text-white/90">{results.executiveSummary}</p>
          </motion.div>
        )}

        {/* Key Recommendations / Action Plan */}
        {results.keyRecommendations && results.keyRecommendations.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 backdrop-blur-sm"
          >
            <h3 className="mb-4 text-sm font-semibold uppercase tracking-wider text-emerald-400">
              Your GTM Action Plan
            </h3>
            <div className="space-y-3">
              {results.keyRecommendations.map((rec, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold ${i === 0 ? 'bg-emerald-500 text-white' : 'bg-white/10 text-white/60'}`}>
                    {i + 1}
                  </span>
                  <p className={`text-sm leading-relaxed ${i === 0 ? 'font-medium text-white' : 'text-white/70'}`}>
                    {rec}
                  </p>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* Decision Attribution Section */}
        {results.decisionAttribution && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05 }}
          >
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center">
                <Cpu className="w-4 h-4 text-purple-400" />
              </div>
              <h3 className="font-medium text-white">Decision Attribution</h3>
            </div>

            {/* Determinism Ratio Bar */}
            <div className="glass-card p-4 rounded-xl mb-3">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm text-white/70">Determinism Ratio</span>
                <span className="text-sm font-bold text-white">
                  {Math.round(results.decisionAttribution.determinismRatio * 100)}%
                </span>
              </div>
              <div className="h-2 bg-white/10 rounded-full overflow-hidden">
                <motion.div
                  className="h-full bg-gradient-to-r from-purple-500 to-blue-500"
                  initial={{ width: 0 }}
                  animate={{ width: `${results.decisionAttribution.determinismRatio * 100}%` }}
                  transition={{ delay: 0.3, duration: 0.8, ease: 'easeOut' }}
                />
              </div>
              <p className="text-xs text-white/50 mt-2">
                Higher = more repeatable & explainable decisions
              </p>
            </div>

            {/* Decision Breakdown */}
            <div className="grid grid-cols-2 gap-2">
              <DecisionCard
                icon={<Cpu className="w-3.5 h-3.5" />}
                label="Algorithm"
                count={results.decisionAttribution.algorithmDecisions}
                color="green"
              />
              <DecisionCard
                icon={<Brain className="w-3.5 h-3.5" />}
                label="LLM"
                count={results.decisionAttribution.llmDecisions}
                color="amber"
              />
              <DecisionCard
                icon={<Wrench className="w-3.5 h-3.5" />}
                label="Tool Calls"
                count={results.decisionAttribution.toolCalls}
                color="blue"
              />
              <DecisionCard
                icon={<Shield className="w-3.5 h-3.5" />}
                label="Governance"
                count={results.decisionAttribution.breakdown.filter(b => b.layer === 'governance').length}
                color="pink"
              />
            </div>

            {/* Layer Breakdown (Collapsible) */}
            {results.decisionAttribution.breakdown.length > 0 && (
              <details className="mt-3">
                <summary className="text-xs text-white/50 cursor-pointer hover:text-white/70 transition-colors">
                  View detailed breakdown ({results.decisionAttribution.breakdown.length} decisions)
                </summary>
                <div className="mt-2 space-y-1.5 max-h-40 overflow-y-auto">
                  {results.decisionAttribution.breakdown.map((decision, i) => (
                    <motion.div
                      key={i}
                      className="flex items-center gap-2 p-2 rounded-lg bg-white/5 text-xs"
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.1 + i * 0.03 }}
                    >
                      <LayerBadge layer={decision.layer} />
                      <span className="text-white/70 truncate flex-1">{decision.component}</span>
                      {decision.executionTimeMs !== undefined && (
                        <span className="text-white/50">{decision.executionTimeMs.toFixed(0)}ms</span>
                      )}
                    </motion.div>
                  ))}
                </div>
              </details>
            )}
          </motion.section>
        )}

        {/* Pipeline Value */}
        {results.totalPipelineValue && results.totalPipelineValue > 0 && (
          <motion.div
            className="glass-card p-4 rounded-xl border border-green-500/20"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.15 }}
          >
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-white/50">Total Pipeline Value</p>
                <p className="text-2xl font-bold text-white">
                  SGD {results.totalPipelineValue.toLocaleString()}
                </p>
              </div>
              <div className="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-green-400" />
              </div>
            </div>
          </motion.div>
        )}

        {/* Leads Section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          <div className="flex items-center gap-2 mb-3">
            <div className="w-8 h-8 rounded-lg bg-blue-500/20 flex items-center justify-center">
              <Users className="w-4 h-4 text-blue-400" />
            </div>
            <h3 className="font-medium text-white">Qualified Leads</h3>
            <span className="ml-auto px-2 py-0.5 text-xs rounded-full bg-blue-500/20 text-blue-300">
              {results.leads.length} found
            </span>
          </div>

          <div className="space-y-2">
            {results.leads.map((lead, i) => (
              <motion.div
                key={lead.id || lead.companyName}
                className="glass-card p-3 rounded-xl group cursor-pointer"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 + i * 0.1 }}
                whileHover={{ scale: 1.02 }}
              >
                <div className="flex items-start justify-between">
                  <div>
                    <h4 className="font-medium text-white text-sm flex items-center gap-2">
                      {lead.companyName}
                      {lead.website && (
                        <a href={lead.website} target="_blank" rel="noopener noreferrer">
                          <ExternalLink className="w-3 h-3 text-white/30 opacity-0 group-hover:opacity-100 transition-opacity" />
                        </a>
                      )}
                    </h4>
                    <p className="text-xs text-white/50 mt-0.5">
                      {lead.industry} • {lead.employeeCount ? `${lead.employeeCount} employees` : 'SME'}
                    </p>
                    {lead.contactName && (
                      <p className="text-xs text-white/40 mt-0.5">
                        Contact: {lead.contactName}{lead.contactTitle ? ` (${lead.contactTitle})` : ''}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    {lead.scoringMethod && (
                      <ScoringMethodBadge method={lead.scoringMethod} />
                    )}
                    <FitScoreBadge score={lead.fitScore} />
                  </div>
                </div>
                {lead.expectedValue && lead.expectedValue > 0 && (
                  <div className="mt-2 pt-2 border-t border-white/5">
                    <span className="text-xs text-white/40">Expected Value: </span>
                    <span className="text-xs text-green-400 font-medium">
                      SGD {lead.expectedValue.toLocaleString()}
                    </span>
                  </div>
                )}
              </motion.div>
            ))}
          </div>

          {results.leads.length > 3 && (
            <button className="w-full mt-3 py-2 text-sm text-blue-400 hover:text-blue-300 transition-colors">
              View all {results.leads.length} leads →
            </button>
          )}
        </motion.section>

        {/* Competitive Landscape Section — ranked table from market intelligence */}
        {results.marketInsights && results.marketInsights.some(mi => mi.category === 'competitive_landscape') && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.28 }}
          >
            {results.marketInsights
              .filter(mi => mi.category === 'competitive_landscape')
              .map((landscape, idx) => (
                <div key={idx}>
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-8 h-8 rounded-lg bg-blue-500/20 flex items-center justify-center">
                      <Brain className="w-4 h-4 text-blue-400" />
                    </div>
                    <div>
                      <h3 className="font-medium text-white">{landscape.title}</h3>
                      <p className="text-xs text-white/50">{landscape.summary}</p>
                    </div>
                  </div>
                  <div className="space-y-1">
                    {landscape.keyFindings.map((entry, i) => (
                      <div
                        key={i}
                        className="text-xs text-white/75 px-3 py-2 rounded-lg bg-white/5 border border-white/5 font-mono leading-snug"
                      >
                        {entry}
                      </div>
                    ))}
                  </div>
                  {landscape.recommendations.length > 0 && (
                    <div className="mt-2 px-3 py-2 rounded-lg bg-blue-500/10 border border-blue-500/20">
                      <p className="text-xs text-blue-300">{landscape.recommendations[0]}</p>
                    </div>
                  )}
                </div>
              ))}
          </motion.section>
        )}

        {/* Market Insights Section */}
        {results.insights.length > 0 && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center">
                <Lightbulb className="w-4 h-4 text-amber-400" />
              </div>
              <h3 className="font-medium text-white">Market Insights</h3>
            </div>

            <div className="space-y-2">
              {results.insights.map((insight, i) => (
                <motion.div
                  key={i}
                  className="flex gap-3 p-3 rounded-xl bg-white/5 border border-white/5"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4 + i * 0.1 }}
                >
                  <TrendingUp className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
                  <p className="text-sm text-white/80">{insight}</p>
                </motion.div>
              ))}
            </div>
          </motion.section>
        )}

        {/* Campaigns Section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <div className="flex items-center gap-2 mb-3">
            <div className="w-8 h-8 rounded-lg bg-red-500/20 flex items-center justify-center">
              <Mail className="w-4 h-4 text-red-400" />
            </div>
            <h3 className="font-medium text-white">Campaign Templates</h3>
          </div>

          <div className="space-y-2">
            {results.campaigns.map((campaign, i) => (
              <motion.div
                key={i}
                className="glass-card p-4 rounded-xl"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.6 + i * 0.1 }}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="px-2 py-0.5 text-xs rounded-full bg-white/10 text-white/70">
                    {campaign.type}
                  </span>
                  {campaign.ready && (
                    <span className="text-xs text-green-400">✓ Ready to use</span>
                  )}
                </div>
                <h4 className="font-medium text-white text-sm">{campaign.title}</h4>
                <button
                  className="mt-3 w-full py-2 text-sm text-center rounded-lg bg-white/5 hover:bg-white/10 text-white/70 hover:text-white transition-all"
                  onClick={() => handleCopyTemplate(campaign.content, i)}
                >
                  {copiedIndex === i ? 'Copied!' : 'View Template'}
                </button>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Market Sizing Section */}
        {results.marketSizing && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.55 }}
          >
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center">
                <TrendingUp className="w-4 h-4 text-purple-400" />
              </div>
              <h3 className="font-medium text-white">Market Sizing</h3>
            </div>

            <div className="glass-card p-4 rounded-xl">
              <div className="grid grid-cols-3 gap-3 mb-3">
                <div className="text-center">
                  <p className="text-[10px] text-white/50 uppercase tracking-wider mb-1">TAM</p>
                  <p className="text-sm font-semibold text-white">{results.marketSizing.tamSgdEstimate ?? 'TBD'}</p>
                </div>
                <div className="text-center border-x border-white/10">
                  <p className="text-[10px] text-white/50 uppercase tracking-wider mb-1">SAM</p>
                  <p className="text-sm font-semibold text-white">{results.marketSizing.samSgdEstimate ?? 'TBD'}</p>
                </div>
                <div className="text-center">
                  <p className="text-[10px] text-white/50 uppercase tracking-wider mb-1">SOM (Yr 1)</p>
                  <p className="text-sm font-semibold text-white">{results.marketSizing.somSgdEstimate ?? 'TBD'}</p>
                </div>
              </div>
              {results.salesMotion && (
                <p className="text-xs text-white/60 border-t border-white/10 pt-3">
                  Sales Motion: <span className="font-semibold text-white/80">{results.salesMotion.primaryMotion}</span>
                  {results.salesMotion.dealSizeSgd && (
                    <> · <span className="text-white/70">{results.salesMotion.dealSizeSgd}</span></>
                  )}
                </p>
              )}
            </div>
          </motion.section>
        )}

        {/* Success Metrics Section */}
        {(results.successMetrics?.length ?? 0) > 0 && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
          >
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center">
                <TrendingUp className="w-4 h-4 text-emerald-400" />
              </div>
              <h3 className="font-medium text-white">Success Metrics</h3>
            </div>

            <div className="glass-card p-4 rounded-xl space-y-2">
              {results.successMetrics!.map((metric, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="mt-1 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400 text-[9px] font-bold">
                    {i + 1}
                  </span>
                  <p className="text-sm text-white/70">{metric}</p>
                </div>
              ))}
            </div>
          </motion.section>
        )}

        {/* Compliance Flags Section */}
        {results.complianceFlags && results.complianceFlags.length > 0 && (
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.65 }}
          >
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center">
                <Shield className="w-4 h-4 text-amber-400" />
              </div>
              <h3 className="font-medium text-white">Compliance Requirements</h3>
            </div>

            <div className="glass-card p-4 rounded-xl">
              <div className="flex flex-wrap gap-2">
                {results.complianceFlags.map((flag, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium bg-amber-500/20 text-amber-300 border border-amber-500/30"
                  >
                    ⚠ {flag}
                  </span>
                ))}
              </div>
            </div>
          </motion.section>
        )}

        {/* CTA block — adapts to auth state */}
        <motion.div
          className="pt-2 pb-2"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
        >
          {!localStorage.getItem('gtm_access_token') && (
            <>
              {/* Locked features preview — only for free users */}
              <div className="mb-4 rounded-xl border border-white/10 bg-white/5 p-4">
                <p className="text-xs text-white/50 uppercase tracking-wider font-medium mb-3">Included in full access</p>
                <div className="space-y-2">
                  {[
                    { icon: Bot, label: 'AI Command Centre — live daily briefing' },
                    { icon: Zap, label: 'Signal Feed — competitor & market alerts' },
                    { icon: Mail, label: 'Automated outreach sequences' },
                    { icon: Users, label: 'Full prospect pipeline (Kanban)' },
                    { icon: TrendingUp, label: 'Revenue attribution & ROI tracking' },
                  ].map(({ icon: Icon, label }) => (
                    <div key={label} className="flex items-center gap-2.5 text-white/40">
                      <Lock className="w-3 h-3 text-white/20 flex-shrink-0" />
                      <Icon className="w-3.5 h-3.5 flex-shrink-0" />
                      <span className="text-xs">{label}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Primary CTA — unauthenticated */}
              <motion.button
                onClick={() => navigate('/register')}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="w-full py-3.5 rounded-xl bg-gradient-to-r from-purple-500 to-blue-600 text-white font-semibold hover:from-purple-600 hover:to-blue-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-purple-500/20"
              >
                <Zap className="w-4 h-4" />
                Unlock Full Dashboard
                <ArrowRight className="w-4 h-4" />
              </motion.button>
              <p className="text-center text-xs text-white/30 mt-2">Free to start · No credit card required</p>

              <div className="mt-3 text-center">
                <button
                  onClick={() => navigate('/login?next=/')}
                  className="text-xs text-white/40 hover:text-white/70 transition-colors"
                >
                  Already have an account? Sign in
                </button>
              </div>
            </>
          )}

          {localStorage.getItem('gtm_access_token') && (
            <>
              {/* Primary CTA — authenticated: go to dashboard */}
              <motion.button
                onClick={() => navigate('/today')}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="w-full py-3.5 rounded-xl bg-gradient-to-r from-purple-500 to-blue-600 text-white font-semibold hover:from-purple-600 hover:to-blue-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-purple-500/20"
              >
                <Zap className="w-4 h-4" />
                Go to Dashboard
                <ArrowRight className="w-4 h-4" />
              </motion.button>
            </>
          )}

          {/* Export stays for free users */}
          <motion.button
            onClick={handleExportReport}
            whileHover={{ scale: 1.01 }}
            whileTap={{ scale: 0.99 }}
            disabled={isExporting}
            className="w-full mt-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white/50 text-sm font-medium hover:bg-white/8 hover:text-white/70 transition-colors flex items-center justify-center gap-2 disabled:opacity-40"
          >
            {isExporting ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
            {isExporting ? 'Exporting...' : 'Download Report (JSON)'}
          </motion.button>
          {exportError && (
            <p className="text-xs text-red-400 text-center mt-1">{exportError}</p>
          )}
        </motion.div>
      </div>
    </motion.div>
  );
}

function FitScoreBadge({ score }: { score: number }) {
  const percentage = Math.round(score * 100);
  const color = score >= 0.8 ? 'green' : score >= 0.6 ? 'amber' : 'red';

  const colors = {
    green: 'from-green-500 to-emerald-500 text-green-100',
    amber: 'from-amber-500 to-orange-500 text-amber-100',
    red: 'from-red-500 to-rose-500 text-red-100',
  };

  return (
    <div
      className={`px-2 py-1 rounded-lg text-xs font-bold bg-gradient-to-r ${colors[color]}`}
    >
      {percentage}%
    </div>
  );
}

function ScoringMethodBadge({ method }: { method: string }) {
  const isAlgorithm = method === 'algorithm';

  return (
    <div
      className={`px-1.5 py-0.5 rounded text-[10px] font-medium flex items-center gap-1 ${
        isAlgorithm
          ? 'bg-green-500/20 text-green-400'
          : 'bg-amber-500/20 text-amber-400'
      }`}
      title={isAlgorithm ? 'Scored by deterministic algorithm' : 'Scored by LLM'}
    >
      {isAlgorithm ? <Cpu className="w-2.5 h-2.5" /> : <Brain className="w-2.5 h-2.5" />}
      {isAlgorithm ? 'ALGO' : 'LLM'}
    </div>
  );
}

function DecisionCard({
  icon,
  label,
  count,
  color
}: {
  icon: React.ReactNode;
  label: string;
  count: number;
  color: 'green' | 'amber' | 'blue' | 'pink';
}) {
  const colorClasses = {
    green: 'bg-green-500/20 text-green-400 border-green-500/30',
    amber: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    blue: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    pink: 'bg-pink-500/20 text-pink-400 border-pink-500/30',
  };

  return (
    <div className={`p-3 rounded-xl border ${colorClasses[color]}`}>
      <div className="flex items-center gap-2">
        <div className={colorClasses[color].split(' ')[0] + ' p-1.5 rounded-lg'}>
          {icon}
        </div>
        <div>
          <p className="text-lg font-bold text-white">{count}</p>
          <p className="text-[10px] text-white/50 uppercase tracking-wider">{label}</p>
        </div>
      </div>
    </div>
  );
}

function LayerBadge({ layer }: { layer: 'cognitive' | 'analytical' | 'operational' | 'governance' }) {
  const config = {
    cognitive: { label: 'LLM', color: 'bg-amber-500/20 text-amber-400' },
    analytical: { label: 'ALGO', color: 'bg-green-500/20 text-green-400' },
    operational: { label: 'TOOL', color: 'bg-blue-500/20 text-blue-400' },
    governance: { label: 'GOV', color: 'bg-pink-500/20 text-pink-400' },
  };

  const { label, color } = config[layer];

  return (
    <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold ${color}`}>
      {label}
    </span>
  );
}
