"""Sequence Engine — manages outreach sequence enrollments and step execution.

The Sequence Engine is the heart of GTM Advisor's execution layer.
It manages the lifecycle of leads through multi-step outreach sequences.

Core operations:
  enroll()        — Enroll a lead in a sequence template
  run_due_steps() — Called daily by APScheduler; finds steps due today,
                    generates personalised content, queues for approval
  pause()         — Pause an enrollment (on reply, manually, opt-out)
  resume()        — Resume a paused enrollment
  complete()      — Mark enrollment as completed

Key design decisions:
  - EVERY step goes through ApprovalQueue before sending
  - Step content is generated by OutreachExecutorAgent
  - No step is sent without explicit human approval
  - Replies pause the enrollment automatically (via webhook)
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from uuid import UUID

import structlog
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from packages.database.src.models import (
    ApprovalQueueItem,
    ApprovalStatus,
    EnrollmentStatus,
    Lead,
    LeadStatus,
    SequenceEnrollment,
    SequenceStep,
    SequenceTemplate,
    SignalEvent,
    SignalUrgency,
)

logger = structlog.get_logger()


class SequenceEngine:
    """Manages the full lifecycle of outreach sequence enrollments."""

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    async def enroll(
        self,
        lead_id: UUID,
        template_id: UUID,
        company_id: UUID,
        trigger_signal_id: UUID | None = None,
        start_date: datetime | None = None,
    ) -> SequenceEnrollment:
        """Enroll a lead in a sequence template.

        Args:
            lead_id: The lead to enroll
            template_id: The sequence template to use
            company_id: The company workspace
            trigger_signal_id: Optional signal that triggered this enrollment
            start_date: When to start (default: now)

        Returns:
            The created SequenceEnrollment

        Raises:
            ValueError: If lead is already enrolled in an active sequence
        """
        # Verify lead belongs to this company
        lead = await self._db.get(Lead, lead_id)
        if not lead or str(lead.company_id) != str(company_id):
            raise ValueError(f"Lead {lead_id} not found in company {company_id}")

        # Check for existing active enrollment
        existing = await self._db.execute(
            select(SequenceEnrollment).where(
                SequenceEnrollment.lead_id == lead_id,
                SequenceEnrollment.status == EnrollmentStatus.ACTIVE,
            )
        )
        if existing.scalar_one_or_none():
            raise ValueError(f"Lead {lead_id} already has an active sequence enrollment")

        # Block re-enrollment of opted-out leads (PDPA compliance)
        opted_out = await self._db.execute(
            select(SequenceEnrollment).where(
                SequenceEnrollment.lead_id == lead_id,
                SequenceEnrollment.status == EnrollmentStatus.OPTED_OUT,
            )
        )
        if opted_out.scalar_one_or_none():
            raise ValueError(f"Lead {lead_id} has opted out and cannot be re-enrolled")

        # Get template to determine first step due date
        template = await self._db.get(SequenceTemplate, template_id)
        if not template:
            raise ValueError(f"Sequence template {template_id} not found")

        start = start_date or datetime.now(UTC)

        enrollment = SequenceEnrollment(
            lead_id=lead_id,
            template_id=template_id,
            company_id=company_id,
            status=EnrollmentStatus.ACTIVE,
            current_step=0,
            next_step_due=start,  # First step due immediately
            trigger_signal_id=trigger_signal_id,
        )
        self._db.add(enrollment)

        # Record consent audit trail (PDPA compliance)
        from packages.database.src.models import AttributionEvent
        self._db.add(AttributionEvent(
            company_id=company_id,
            lead_id=lead_id,
            event_type="consent_recorded",
            recorded_by="system",
            metadata_json={
                "purpose": "MARKETING",
                "source": "sequence_enrollment",
                "template_id": str(template_id),
            },
        ))

        await self._db.commit()
        await self._db.refresh(enrollment)

        logger.info("enrollment_created", lead_id=str(lead_id), template=template.name)
        return enrollment

    async def run_due_steps(self) -> int:
        """Find and queue all due sequence steps for approval.

        Called daily by APScheduler. For each enrollment with next_step_due
        <= now, generates personalised email content and adds to ApprovalQueue.

        Returns:
            Number of steps queued for approval
        """
        now = datetime.now(UTC)

        # Auto-reject expired approval items so the queue stays clean.
        expired_stmt = select(ApprovalQueueItem).where(
            ApprovalQueueItem.status == ApprovalStatus.PENDING,
            ApprovalQueueItem.expires_at <= now,
        )
        expired_items = (await self._db.execute(expired_stmt)).scalars().all()
        for item in expired_items:
            item.status = ApprovalStatus.REJECTED
            logger.info(
                "approval_item_expired",
                item_id=str(item.id),
                lead_id=str(item.lead_id),
            )
        if expired_items:
            await self._db.commit()

        queued = 0

        stmt = (
            select(SequenceEnrollment)
            .where(
                SequenceEnrollment.status == EnrollmentStatus.ACTIVE,
                SequenceEnrollment.next_step_due <= now,
            )
            .limit(100)  # Process max 100 enrollments per run
        )
        enrollments = (await self._db.execute(stmt)).scalars().all()

        for enrollment in enrollments:
            try:
                count = await self._process_enrollment_step(enrollment)
                queued += count
            except Exception as e:
                logger.error(
                    "enrollment_step_failed",
                    enrollment_id=str(enrollment.id),
                    error=str(e),
                )

        if queued > 0:
            logger.info("sequence_steps_queued", count=queued)
        return queued

    async def _process_enrollment_step(self, enrollment: SequenceEnrollment) -> int:
        """Process the current step for an enrollment.

        Returns:
            1 if step was queued, 0 if enrollment completed/skipped
        """
        # Get the template steps
        template = await self._db.get(SequenceTemplate, enrollment.template_id)
        if not template:
            return 0

        steps_result = await self._db.execute(
            select(SequenceStep)
            .where(SequenceStep.template_id == enrollment.template_id)
            .order_by(SequenceStep.step_number)
        )
        steps = steps_result.scalars().all()

        if enrollment.current_step >= len(steps):
            # All steps done
            enrollment.status = EnrollmentStatus.COMPLETED
            enrollment.completed_at = datetime.now(UTC)
            await self._db.commit()
            return 0

        step = steps[enrollment.current_step]
        lead = await self._db.get(Lead, enrollment.lead_id)
        if not lead:
            return 0

        # Generate personalised content
        subject, body = await self._personalise_step(step, lead, template)

        # Create approval queue item
        approval_item = ApprovalQueueItem(
            company_id=enrollment.company_id,
            enrollment_id=enrollment.id,
            step_number=enrollment.current_step,
            lead_id=enrollment.lead_id,
            status=ApprovalStatus.PENDING,
            proposed_subject=subject,
            proposed_body=body,
            to_email=lead.contact_email or "",
            to_name=lead.contact_name,
            sequence_name=template.name,
            expires_at=datetime.now(UTC) + timedelta(days=3),  # Expire after 3 days
        )
        self._db.add(approval_item)

        # Advance to next step — due date is relative to enrollment start, not now
        next_step_index = enrollment.current_step + 1
        if next_step_index < len(steps):
            next_step = steps[next_step_index]
            enrollment.next_step_due = enrollment.enrolled_at + timedelta(days=next_step.day_offset)
        else:
            enrollment.next_step_due = None  # No more steps — won't be picked up again
        enrollment.current_step = next_step_index

        await self._db.commit()
        logger.info(
            "approval_item_created",
            lead=lead.contact_email,
            step=enrollment.current_step,
            sequence=template.name,
        )
        return 1

    async def _personalise_step(
        self,
        step: SequenceStep,
        lead: Lead,
        _template: SequenceTemplate,
    ) -> tuple[str, str]:
        """Generate personalised subject and body for a step.

        Simple template substitution — LLM personalisation is done by
        OutreachExecutorAgent when the approval item is sent.
        This creates a preview for the approval queue.
        """
        first_name = (lead.contact_name or "").split()[0] if lead.contact_name else "there"
        company_name = lead.lead_company_name or "your company"

        # Substitute template variables
        subject = step.subject_pattern.replace("{first_name}", first_name)
        subject = subject.replace("{company_name}", company_name)
        subject = subject.replace("{industry}", lead.lead_company_industry or "your industry")

        # Body placeholder — will be LLM-personalised on approval
        body = (
            f"Hi {first_name},\n\n"
            f"[This email will be personalised when approved. Step: {step.step_type}]\n\n"
            f"Instructions for personalisation:\n{step.body_instructions or 'Use the campaign brief to write a relevant, concise email.'}\n\n"
            f"Context: {lead.contact_name} at {company_name}, {lead.contact_title or 'unknown role'}\n"
        )

        return subject, body

    async def pause(
        self,
        enrollment_id: UUID,
        reason: str = "manual",
    ) -> None:
        """Pause an active enrollment."""
        enrollment = await self._db.get(SequenceEnrollment, enrollment_id)
        if enrollment and enrollment.status == EnrollmentStatus.ACTIVE:
            enrollment.status = EnrollmentStatus.PAUSED
            enrollment.paused_at = datetime.now(UTC)
            enrollment.pause_reason = reason
            await self._db.commit()

    async def resume(self, enrollment_id: UUID) -> None:
        """Resume a paused enrollment."""
        enrollment = await self._db.get(SequenceEnrollment, enrollment_id)
        if enrollment and enrollment.status == EnrollmentStatus.PAUSED:
            enrollment.status = EnrollmentStatus.ACTIVE
            enrollment.paused_at = None
            enrollment.pause_reason = None
            enrollment.next_step_due = datetime.now(UTC)
            await self._db.commit()

    async def auto_enroll_from_signals(
        self,
        company_id: str,
        db: AsyncSession,
    ) -> int:
        """Enrol leads into Signal-Triggered playbook when high-relevance signals exist.

        Finds all UNACTED signals (urgency in ['high', 'immediate'] OR
        relevance_score >= 0.65) for this company created in the last 24 hours.
        For each qualifying lead that is NOT already enrolled in an active
        sequence, creates a new SequenceEnrollment linked to the first
        qualifying signal.

        Args:
            company_id: UUID string of the company workspace.
            db: Async database session to use for all queries and writes.

        Returns:
            Count of new enrollments created.
        """
        try:
            from uuid import UUID as _UUID

            company_uuid = _UUID(company_id)
            cutoff = datetime.now(tz=UTC) - timedelta(hours=24)

            # --- Step 1: find qualifying signals ---
            signal_stmt = (
                select(SignalEvent)
                .where(
                    SignalEvent.company_id == company_uuid,
                    SignalEvent.created_at >= cutoff,
                    SignalEvent.is_actioned.is_(False),
                    or_(
                        SignalEvent.urgency.in_([
                            SignalUrgency.IMMEDIATE,
                            SignalUrgency.THIS_WEEK,  # "high" maps to THIS_WEEK
                        ]),
                        SignalEvent.relevance_score >= 0.65,
                    ),
                )
                .order_by(SignalEvent.relevance_score.desc())
                .limit(10)
            )
            signals = (await db.execute(signal_stmt)).scalars().all()

            if not signals:
                return 0

            trigger_signal = signals[0]  # Use highest-relevance signal as trigger

            # --- Step 2: find Signal-Triggered sequence template ---
            template_stmt = (
                select(SequenceTemplate)
                .where(
                    SequenceTemplate.is_active.is_(True),
                    or_(
                        SequenceTemplate.company_id == company_uuid,
                        SequenceTemplate.company_id.is_(None),  # system templates
                    ),
                    or_(
                        SequenceTemplate.playbook_type == "signal_triggered",
                        SequenceTemplate.name.ilike("%signal%"),
                    ),
                )
                .order_by(
                    # Prefer company-specific template over system template
                    SequenceTemplate.company_id.desc().nullslast(),
                )
                .limit(1)
            )
            template = (await db.execute(template_stmt)).scalar_one_or_none()

            if template is None:
                # Fall back to any active template for this company
                fallback_stmt = (
                    select(SequenceTemplate)
                    .where(
                        SequenceTemplate.is_active.is_(True),
                        or_(
                            SequenceTemplate.company_id == company_uuid,
                            SequenceTemplate.company_id.is_(None),
                        ),
                    )
                    .limit(1)
                )
                template = (await db.execute(fallback_stmt)).scalar_one_or_none()

            if template is None:
                logger.info(
                    "auto_enroll_no_template",
                    company_id=company_id,
                )
                return 0

            # --- Step 3: find eligible leads ---
            leads_stmt = (
                select(Lead)
                .where(
                    Lead.company_id == company_uuid,
                    Lead.status.notin_([LeadStatus.LOST]),
                )
                .order_by(Lead.overall_score.desc())
                .limit(20)
            )
            leads = (await db.execute(leads_stmt)).scalars().all()

            if not leads:
                return 0

            # --- Step 4: filter out leads already in an active enrollment ---
            enrolled_lead_ids_stmt = select(SequenceEnrollment.lead_id).where(
                SequenceEnrollment.company_id == company_uuid,
                SequenceEnrollment.status == EnrollmentStatus.ACTIVE,
            )
            enrolled_ids = set(
                (await db.execute(enrolled_lead_ids_stmt)).scalars().all()
            )

            # --- Step 5: enroll qualifying leads ---
            new_enrollments = 0
            for lead in leads:
                if lead.id in enrolled_ids:
                    continue
                # Require a non-empty email address
                if not lead.contact_email:
                    continue
                try:
                    # Use the existing enroll() method which handles validation
                    # and commits inside. We pass db indirectly via self._db —
                    # temporarily swap so enroll() uses the caller's session.
                    original_db = self._db
                    self._db = db
                    try:
                        await self.enroll(
                            lead_id=lead.id,
                            template_id=template.id,
                            company_id=company_uuid,
                            trigger_signal_id=trigger_signal.id,
                        )
                    finally:
                        self._db = original_db
                    new_enrollments += 1
                except ValueError:
                    # Already enrolled or other validation issue — skip silently
                    pass

            if new_enrollments > 0:
                logger.info(
                    "auto_enrolled_from_signals",
                    company_id=company_id,
                    count=new_enrollments,
                    template=template.name,
                    trigger_signal_id=str(trigger_signal.id),
                )
            return new_enrollments

        except Exception as e:
            logger.warning(
                "auto_enroll_from_signals_failed",
                company_id=company_id,
                error=str(e),
            )
            return 0

    async def pause_on_reply(self, lead_id: UUID) -> int:
        """Pause ALL active enrollments for a lead that replied.

        Called when a reply webhook is received.

        Returns:
            Number of enrollments paused
        """
        stmt = select(SequenceEnrollment).where(
            SequenceEnrollment.lead_id == lead_id,
            SequenceEnrollment.status == EnrollmentStatus.ACTIVE,
        )
        enrollments = (await self._db.execute(stmt)).scalars().all()
        for enrollment in enrollments:
            enrollment.status = EnrollmentStatus.PAUSED
            enrollment.paused_at = datetime.now(UTC)
            enrollment.pause_reason = "reply_received"
        await self._db.commit()
        return len(enrollments)
