"""Initial schema

Revision ID: 54b79669bb7d
Revises:
Create Date: 2026-01-29 20:38:50.728181

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54b79669bb7d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column(
            "tier", sa.Enum("FREE", "TIER1", "TIER2", name="subscriptiontier"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("daily_requests", sa.Integer(), nullable=True),
        sa.Column("last_request_date", sa.DateTime(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_subtype", sa.String(length=50), nullable=True),
        sa.Column("agent_id", sa.String(length=50), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_agent_id"), "audit_logs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_session_id"), "audit_logs", ["session_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(
        "ix_audit_logs_timestamp_event", "audit_logs", ["timestamp", "event_type"], unique=False
    )
    op.create_index(
        "ix_audit_logs_user_event", "audit_logs", ["user_id", "event_type"], unique=False
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("founded_year", sa.String(length=10), nullable=True),
        sa.Column("headquarters", sa.String(length=200), nullable=True),
        sa.Column("employee_count", sa.String(length=50), nullable=True),
        sa.Column("funding_stage", sa.String(length=100), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=True),
        sa.Column("products", sa.JSON(), nullable=True),
        sa.Column("goals", sa.JSON(), nullable=True),
        sa.Column("challenges", sa.JSON(), nullable=True),
        sa.Column("competitors", sa.JSON(), nullable=True),
        sa.Column("target_markets", sa.JSON(), nullable=True),
        sa.Column("value_proposition", sa.Text(), nullable=True),
        sa.Column("enrichment_confidence", sa.Float(), nullable=True),
        sa.Column("last_enriched_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_companies_owner_id", "companies", ["owner_id"], unique=False)
    op.create_table(
        "consents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("data_subject_id", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "MARKETING", "SALES", "ANALYTICS", "PROFILING", "THIRD_PARTY", name="consentpurpose"
            ),
            nullable=False,
        ),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consents_data_subject_id"), "consents", ["data_subject_id"], unique=False
    )
    op.create_index(
        "ix_consents_data_subject_purpose", "consents", ["data_subject_id", "purpose"], unique=False
    )
    op.create_index("ix_consents_user_id", "consents", ["user_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=50), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IDLE", "RUNNING", "COMPLETED", "ERROR", name="agentrunstatus"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_runs_agent_id", "agent_runs", ["agent_id"], unique=False)
    op.create_index(
        "ix_agent_runs_company_agent", "agent_runs", ["company_id", "agent_id"], unique=False
    )
    op.create_index("ix_agent_runs_company_id", "agent_runs", ["company_id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="analysisstatus"),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("current_agent", sa.String(length=50), nullable=True),
        sa.Column("completed_agents", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("key_recommendations", sa.JSON(), nullable=True),
        sa.Column("market_insights", sa.JSON(), nullable=True),
        sa.Column("competitor_analysis", sa.JSON(), nullable=True),
        sa.Column("customer_personas", sa.JSON(), nullable=True),
        sa.Column("leads", sa.JSON(), nullable=True),
        sa.Column("campaign_brief", sa.JSON(), nullable=True),
        sa.Column("total_confidence", sa.Float(), nullable=True),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column("agents_used", sa.JSON(), nullable=True),
        sa.Column("algorithm_decisions", sa.Integer(), nullable=True),
        sa.Column("llm_decisions", sa.Integer(), nullable=True),
        sa.Column("tool_calls", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_analyses_company_id", "analyses", ["company_id"], unique=False)
    op.create_index("ix_analyses_status", "analyses", ["status"], unique=False)
    op.create_index("ix_analyses_user_id", "analyses", ["user_id"], unique=False)
    op.create_table(
        "competitors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("weaknesses", sa.JSON(), nullable=True),
        sa.Column("opportunities", sa.JSON(), nullable=True),
        sa.Column("threats", sa.JSON(), nullable=True),
        sa.Column(
            "threat_level", sa.Enum("LOW", "MEDIUM", "HIGH", name="threatlevel"), nullable=True
        ),
        sa.Column("positioning", sa.Text(), nullable=True),
        sa.Column("pricing_info", sa.JSON(), nullable=True),
        sa.Column("our_advantages", sa.JSON(), nullable=True),
        sa.Column("their_advantages", sa.JSON(), nullable=True),
        sa.Column("key_objection_handlers", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_competitors_company_id", "competitors", ["company_id"], unique=False)
    op.create_index("ix_competitors_threat_level", "competitors", ["threat_level"], unique=False)
    op.create_table(
        "icps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column("company_size", sa.String(length=100), nullable=True),
        sa.Column("revenue_range", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("tech_stack", sa.String(length=200), nullable=True),
        sa.Column("buying_triggers", sa.JSON(), nullable=True),
        sa.Column("pain_points", sa.JSON(), nullable=True),
        sa.Column("needs", sa.JSON(), nullable=True),
        sa.Column("matching_companies_count", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_icps_company_id", "icps", ["company_id"], unique=False)
    op.create_table(
        "market_insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("insight_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("full_content", sa.Text(), nullable=True),
        sa.Column("impact_level", sa.String(length=20), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("source_name", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("recommended_actions", sa.JSON(), nullable=True),
        sa.Column("related_agents", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_market_insights_company_id", "market_insights", ["company_id"], unique=False
    )
    op.create_index(
        "ix_market_insights_created_at", "market_insights", ["created_at"], unique=False
    )
    op.create_index("ix_market_insights_type", "market_insights", ["insight_type"], unique=False)
    op.create_table(
        "strategy_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("agents_active", sa.Integer(), nullable=True),
        sa.Column("agents_total", sa.Integer(), nullable=True),
        sa.Column("tasks_completed", sa.Integer(), nullable=True),
        sa.Column("avg_confidence", sa.Float(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_strategy_runs_company_id", "strategy_runs", ["company_id"], unique=False)
    op.create_table(
        "agent_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_run_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=50), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=300), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_run_id"],
            ["strategy_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_activities_company_id", "agent_activities", ["company_id"], unique=False
    )
    op.create_index(
        "ix_agent_activities_created_at", "agent_activities", ["created_at"], unique=False
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("icp_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("objective", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "PAUSED", "COMPLETED", name="campaignstatus"),
            nullable=True,
        ),
        sa.Column("target_personas", sa.JSON(), nullable=True),
        sa.Column("target_industries", sa.JSON(), nullable=True),
        sa.Column("target_company_sizes", sa.JSON(), nullable=True),
        sa.Column("key_messages", sa.JSON(), nullable=True),
        sa.Column("value_propositions", sa.JSON(), nullable=True),
        sa.Column("call_to_action", sa.String(length=200), nullable=True),
        sa.Column("channels", sa.JSON(), nullable=True),
        sa.Column("email_templates", sa.JSON(), nullable=True),
        sa.Column("linkedin_posts", sa.JSON(), nullable=True),
        sa.Column("ad_copy", sa.JSON(), nullable=True),
        sa.Column("landing_page_copy", sa.JSON(), nullable=True),
        sa.Column("blog_outlines", sa.JSON(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["icp_id"],
            ["icps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_campaigns_company_id", "campaigns", ["company_id"], unique=False)
    op.create_index("ix_campaigns_status", "campaigns", ["status"], unique=False)
    op.create_table(
        "competitor_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("is_dismissed", sa.Boolean(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_competitor_alerts_competitor_id", "competitor_alerts", ["competitor_id"], unique=False
    )
    op.create_index("ix_competitor_alerts_is_read", "competitor_alerts", ["is_read"], unique=False)
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("icp_id", sa.UUID(), nullable=True),
        sa.Column("lead_company_name", sa.String(length=200), nullable=False),
        sa.Column("lead_company_website", sa.String(length=255), nullable=True),
        sa.Column("lead_company_industry", sa.String(length=100), nullable=True),
        sa.Column("lead_company_size", sa.String(length=50), nullable=True),
        sa.Column("lead_company_description", sa.Text(), nullable=True),
        sa.Column("contact_name", sa.String(length=100), nullable=True),
        sa.Column("contact_title", sa.String(length=100), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_linkedin", sa.String(length=255), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column("intent_score", sa.Integer(), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "QUALIFIED", "CONTACTED", "CONVERTED", "LOST", name="leadstatus"),
            nullable=True,
        ),
        sa.Column("qualification_reasons", sa.JSON(), nullable=True),
        sa.Column("disqualification_reasons", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("contacted_at", sa.DateTime(), nullable=True),
        sa.Column("converted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["icp_id"],
            ["icps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_leads_company_id", "leads", ["company_id"], unique=False)
    op.create_index("ix_leads_overall_score", "leads", ["overall_score"], unique=False)
    op.create_index("ix_leads_status", "leads", ["status"], unique=False)
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("icp_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("avatar", sa.String(length=10), nullable=True),
        sa.Column("age_range", sa.String(length=20), nullable=True),
        sa.Column("experience_years", sa.String(length=20), nullable=True),
        sa.Column("education", sa.String(length=100), nullable=True),
        sa.Column("goals", sa.JSON(), nullable=True),
        sa.Column("challenges", sa.JSON(), nullable=True),
        sa.Column("objections", sa.JSON(), nullable=True),
        sa.Column("preferred_channels", sa.JSON(), nullable=True),
        sa.Column("messaging_hooks", sa.JSON(), nullable=True),
        sa.Column("content_preferences", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["icp_id"],
            ["icps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_personas_icp_id", "personas", ["icp_id"], unique=False)
    op.create_table(
        "strategy_phases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_run_id", sa.UUID(), nullable=False),
        sa.Column("phase_key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETE", name="phasestatus"),
            nullable=True,
        ),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_run_id"],
            ["strategy_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_strategy_phases_run_id", "strategy_phases", ["strategy_run_id"], unique=False
    )
    op.create_table(
        "strategy_recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("strategy_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="recommendationpriority"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_agents", sa.JSON(), nullable=True),
        sa.Column("impact", sa.String(length=200), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "DISMISSED", name="recommendationstatus"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_run_id"],
            ["strategy_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_strategy_recommendations_company_id",
        "strategy_recommendations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_strategy_recommendations_status", "strategy_recommendations", ["status"], unique=False
    )
    op.create_table(
        "generated_content",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tone", sa.String(length=20), nullable=True),
        sa.Column("target_persona", sa.String(length=100), nullable=True),
        sa.Column("topic", sa.String(length=300), nullable=True),
        sa.Column("key_points", sa.JSON(), nullable=True),
        sa.Column("include_cta", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generated_content_company_id", "generated_content", ["company_id"], unique=False
    )
    op.create_index(
        "ix_generated_content_type", "generated_content", ["content_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_generated_content_type", table_name="generated_content")
    op.drop_index("ix_generated_content_company_id", table_name="generated_content")
    op.drop_table("generated_content")
    op.drop_index("ix_strategy_recommendations_status", table_name="strategy_recommendations")
    op.drop_index("ix_strategy_recommendations_company_id", table_name="strategy_recommendations")
    op.drop_table("strategy_recommendations")
    op.drop_index("ix_strategy_phases_run_id", table_name="strategy_phases")
    op.drop_table("strategy_phases")
    op.drop_index("ix_personas_icp_id", table_name="personas")
    op.drop_table("personas")
    op.drop_index("ix_leads_status", table_name="leads")
    op.drop_index("ix_leads_overall_score", table_name="leads")
    op.drop_index("ix_leads_company_id", table_name="leads")
    op.drop_table("leads")
    op.drop_index("ix_competitor_alerts_is_read", table_name="competitor_alerts")
    op.drop_index("ix_competitor_alerts_competitor_id", table_name="competitor_alerts")
    op.drop_table("competitor_alerts")
    op.drop_index("ix_campaigns_status", table_name="campaigns")
    op.drop_index("ix_campaigns_company_id", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index("ix_agent_activities_created_at", table_name="agent_activities")
    op.drop_index("ix_agent_activities_company_id", table_name="agent_activities")
    op.drop_table("agent_activities")
    op.drop_index("ix_strategy_runs_company_id", table_name="strategy_runs")
    op.drop_table("strategy_runs")
    op.drop_index("ix_market_insights_type", table_name="market_insights")
    op.drop_index("ix_market_insights_created_at", table_name="market_insights")
    op.drop_index("ix_market_insights_company_id", table_name="market_insights")
    op.drop_table("market_insights")
    op.drop_index("ix_icps_company_id", table_name="icps")
    op.drop_table("icps")
    op.drop_index("ix_competitors_threat_level", table_name="competitors")
    op.drop_index("ix_competitors_company_id", table_name="competitors")
    op.drop_table("competitors")
    op.drop_index("ix_analyses_user_id", table_name="analyses")
    op.drop_index("ix_analyses_status", table_name="analyses")
    op.drop_index("ix_analyses_company_id", table_name="analyses")
    op.drop_table("analyses")
    op.drop_index("ix_agent_runs_company_id", table_name="agent_runs")
    op.drop_index("ix_agent_runs_company_agent", table_name="agent_runs")
    op.drop_index("ix_agent_runs_agent_id", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_consents_user_id", table_name="consents")
    op.drop_index("ix_consents_data_subject_purpose", table_name="consents")
    op.drop_index(op.f("ix_consents_data_subject_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index("ix_companies_owner_id", table_name="companies")
    op.drop_table("companies")
    op.drop_index("ix_audit_logs_user_event", table_name="audit_logs")
    op.drop_index("ix_audit_logs_timestamp_event", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_session_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_agent_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
