"""Layer 4: Knowledge MCP server — gives agents access to the marketing knowledge base.

Provides structured access to:
  - Layer 1 (frameworks.py): static constants, always available
  - Layer 3 (extractor.py): semantic search over Qdrant book chunks

Agents call this server via `await mcp.get_framework(...)` or
`await mcp.search_knowledge(...)` in their `_do()` methods.

Usage example (in an agent's _do method):
    mcp = KnowledgeMCPServer()
    frameworks = await mcp.get_framework("CIALDINI_PRINCIPLES")
    excerpts = await mcp.search_knowledge(
        "how to write a cold email for Singapore SMEs",
        agent_context="campaign_architect",
    )
    messaging = await mcp.get_messaging_framework("cold outreach")
"""

from __future__ import annotations

import json
import logging
import os
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Domain guide store constants
# ---------------------------------------------------------------------------

# Guides live in data/knowledge/guides/{slug}.json — generated by
# scripts/synthesize_domain_guides.py from Qdrant book chunks.
_GUIDES_DIR = Path(__file__).resolve().parents[3] / "data" / "knowledge" / "guides"

# Maps agent names (kebab-case) to guide slugs in priority order.
# Slugs without a corresponding .json file are silently skipped at runtime.
_AGENT_GUIDE_MAP: dict[str, list[str]] = {
    "campaign-architect": [
        "digital_awareness_campaign",
        "cold_email_sequence",
        "content_marketing_b2b",
        "campaign_measurement",
        "linkedin_b2b_campaign",
        "singapore_pdpa_gtm",
    ],
    "gtm-strategist": [
        "gtm_motion_selection",
        "singapore_market_entry",
        "b2b_saas_pricing",
        "singapore_psg_grants",
        "singapore_pdpa_gtm",
        "singapore_asean_expansion",
    ],
    "customer-profiler": [
        "icp_development",
        "buyer_persona_research",
        "buyer_journey_mapping",
        "singapore_psg_grants",
    ],
    "competitor-analyst": [
        "competitive_intelligence",
        "positioning_differentiation",
        "swot_to_strategy",
    ],
    "market-intelligence": [
        "market_sizing",
        "industry_trend_analysis",
        "singapore_asean_expansion",
    ],
    "lead-hunter": [
        "lead_qualification",
        "signal_based_prospecting",
        "singapore_psg_grants",
    ],
    "signal-monitor": [
        "signal_based_prospecting",
        "industry_trend_analysis",
        "competitive_intelligence",
    ],
    "lead-enrichment": [
        "lead_qualification",
        "singapore_pdpa_gtm",
        "buyer_persona_research",
    ],
    "workforce-architect": [
        "campaign_measurement",
        "gtm_motion_selection",
        "content_marketing_b2b",
    ],
}

# Keywords per guide slug used to rank guides by relevance to a task string.
_GUIDE_RELEVANCE_KEYWORDS: dict[str, list[str]] = {
    "digital_awareness_campaign": [
        "awareness", "campaign", "launch", "digital", "reach", "brand", "visibility",
    ],
    "cold_email_sequence": [
        "cold", "email", "outreach", "sequence", "prospect", "cold outreach",
    ],
    "content_marketing_b2b": [
        "content", "blog", "thought leadership", "inbound", "article", "publish",
    ],
    "campaign_measurement": [
        "measurement", "attribution", "roi", "analytics", "track", "metric", "kpi",
    ],
    "linkedin_b2b_campaign": [
        "linkedin", "social", "ads", "paid", "abm", "account-based", "sponsored",
    ],
    "gtm_motion_selection": [
        "gtm", "go-to-market", "motion", "plg", "slg", "sales-led", "product-led",
    ],
    "singapore_market_entry": [
        "singapore", "entry", "market entry", "apac", "local", "sg", "expand",
    ],
    "b2b_saas_pricing": [
        "price", "pricing", "saas", "subscription", "tier", "monetize", "revenue",
    ],
    "icp_development": [
        "icp", "ideal customer", "firmographic", "target", "segment", "profile",
    ],
    "buyer_persona_research": [
        "persona", "buyer", "decision maker", "stakeholder", "role", "champion",
    ],
    "buyer_journey_mapping": [
        "journey", "funnel", "stages", "consideration", "decision", "buying process",
    ],
    "competitive_intelligence": [
        "competitor", "intelligence", "research", "landscape", "swot", "competitive",
    ],
    "positioning_differentiation": [
        "position", "differentiation", "unique", "value prop", "messaging", "differentiate",
    ],
    "swot_to_strategy": [
        "swot", "strategy", "strengths", "weaknesses", "opportunities", "threats",
    ],
    "market_sizing": [
        "tam", "sam", "som", "market size", "sizing", "addressable", "total market",
    ],
    "industry_trend_analysis": [
        "trend", "market trend", "industry", "signal", "macro", "emerging", "shift",
    ],
    "lead_qualification": [
        "qualify", "qualification", "bant", "meddic", "score", "fit", "criteria",
    ],
    "signal_based_prospecting": [
        "signal", "trigger", "intent", "prospecting", "buying signal", "intent data",
    ],
    "singapore_psg_grants": [
        "psg", "edg", "grant", "productivity solutions grant", "enterprise development grant",
        "imda", "entsg", "funding support", "vendor", "approved vendor",
    ],
    "singapore_pdpa_gtm": [
        "pdpa", "pdpc", "dnc", "do not call", "consent", "personal data", "dpo",
        "data protection", "opt-out", "compliance", "marketing compliance",
    ],
    "singapore_asean_expansion": [
        "asean", "mra", "regional", "expansion", "overseas", "apac", "malaysia",
        "indonesia", "vietnam", "southeast asia", "market readiness",
    ],
}


class KnowledgeMCPServer:
    """MCP server giving agents structured access to the marketing knowledge base.

    Layer 1 methods (get_framework, get_messaging_framework, get_campaign_brief_template,
    get_objection_handlers) are always available — they use static constants.

    Layer 3 methods (search_knowledge) require Qdrant and OpenAI to be configured.
    They degrade gracefully: if unavailable, they return relevant Layer 1 content instead.
    """

    def __init__(self, openai_api_key: str | None = None, qdrant_url: str | None = None) -> None:
        self._openai_api_key = openai_api_key or os.environ.get("OPENAI_API_KEY", "").strip()
        self._qdrant_url = qdrant_url or os.environ.get("QDRANT_URL", "").strip()
        self._qdrant_path = os.environ.get("QDRANT_PATH", "").strip()
        self._openai_client = None
        self._qdrant_client = None

    # ------------------------------------------------------------------
    # Layer 1: Static framework access
    # ------------------------------------------------------------------

    async def get_framework(self, framework_name: str) -> dict:
        """Get a specific marketing framework by name.

        Args:
            framework_name: One of the constants in frameworks.py, e.g.
                'CIALDINI_PRINCIPLES', 'STP_FRAMEWORK', 'SALES_QUALIFICATION',
                'MESSAGING_FRAMEWORKS', 'OGILVY_PRINCIPLES', 'GTM_FRAMEWORKS',
                'ICP_FRAMEWORK', 'SINGAPORE_SME_CONTEXT', 'MADE_TO_STICK_SUCCESS',
                'CAMPAIGN_BRIEF_TEMPLATE', 'OBJECTION_HANDLING_FRAMEWORK',
                'RACE_FRAMEWORK', 'MARKETING_MIX_4P', 'PORTER_FIVE_FORCES'.

        Returns:
            The framework dict, plus metadata about its source books.
            Returns an error dict if framework_name is not found.
        """
        import packages.knowledge.src.frameworks as fw  # noqa: PLC0415
        from packages.knowledge.src.book_index import get_attribution_for_framework  # noqa: PLC0415

        framework = getattr(fw, framework_name, None)
        if framework is None:
            available = fw.ALL_FRAMEWORK_NAMES
            return {
                "error": f"Framework '{framework_name}' not found.",
                "available_frameworks": available,
            }

        attribution = get_attribution_for_framework(framework_name)
        return {
            "framework_name": framework_name,
            "content": framework,
            "source_books": [
                {"title": b["title"], "authors": b.get("authors", [])}
                for b in attribution
            ],
        }

    async def get_messaging_framework(self, use_case: str) -> dict:
        """Get the best messaging framework for a given use case.

        Selects from MESSAGING_FRAMEWORKS based on keyword matching against
        the use_case string.

        Args:
            use_case: Natural language description, e.g. 'cold email outreach',
                'product demo', 'case study', 'transformation story',
                'nurture sequence'.

        Returns:
            Dict with 'recommended_framework', 'framework_content', and
            'rationale'.
        """
        from packages.knowledge.src.frameworks import MESSAGING_FRAMEWORKS  # noqa: PLC0415

        use_case_lower = use_case.lower()

        # Scoring map: (keywords, framework_key, rationale)
        rules: list[tuple[list[str], str, str]] = [
            (
                ["cold", "outreach", "cold email", "prospecting", "cold call"],
                "PAS",
                "PAS (Problem-Agitate-Solution) is the highest-converting framework for cold outreach because it demonstrates empathy before selling.",
            ),
            (
                ["case study", "testimonial", "story", "reference", "success story"],
                "STAR",
                "STAR (Situation-Task-Action-Result) gives case studies a credible, narrative structure that makes results believable.",
            ),
            (
                ["demo", "product", "feature", "specification", "capability"],
                "FAB",
                "FAB (Features-Advantages-Benefits) translates product capabilities into customer value during product demonstrations.",
            ),
            (
                ["transformation", "before after", "vision", "homepage", "hero", "brand"],
                "BAB",
                "BAB (Before-After-Bridge) paints the transformation story, ideal for homepage copy and executive pitches.",
            ),
            (
                ["landing page", "ad", "awareness", "nurture", "email marketing", "sequence"],
                "AIDA",
                "AIDA (Attention-Interest-Desire-Action) is the classic full-funnel framework for awareness-to-conversion communications.",
            ),
            (
                ["strategy", "workshop", "aspiration", "growth", "vision", "executive"],
                "SOAR",
                "SOAR (Strengths-Opportunities-Aspirations-Results) works for strategic, aspiration-led executive conversations.",
            ),
        ]

        for keywords, framework_key, rationale in rules:
            if any(kw in use_case_lower for kw in keywords):
                return {
                    "use_case": use_case,
                    "recommended_framework": framework_key,
                    "rationale": rationale,
                    "framework_content": MESSAGING_FRAMEWORKS.get(framework_key, {}),
                    "all_frameworks": {k: v.get("best_for", "") for k, v in MESSAGING_FRAMEWORKS.items()},
                }

        # Default: AIDA is most universal
        return {
            "use_case": use_case,
            "recommended_framework": "AIDA",
            "rationale": "AIDA is the most universally applicable messaging framework when no specific use case is matched.",
            "framework_content": MESSAGING_FRAMEWORKS.get("AIDA", {}),
            "all_frameworks": {k: v.get("best_for", "") for k, v in MESSAGING_FRAMEWORKS.items()},
        }

    async def get_campaign_brief_template(self) -> dict:
        """Return a structured campaign brief template based on best practices.

        Returns:
            The CAMPAIGN_BRIEF_TEMPLATE dict with usage guidance.
        """
        from packages.knowledge.src.frameworks import (  # noqa: PLC0415
            CAMPAIGN_BRIEF_TEMPLATE,
            CIALDINI_PRINCIPLES,
            MESSAGING_FRAMEWORKS,
        )

        return {
            "template": CAMPAIGN_BRIEF_TEMPLATE,
            "cialdini_options": list(CIALDINI_PRINCIPLES.keys()),
            "messaging_framework_options": list(MESSAGING_FRAMEWORKS.keys()),
            "usage": (
                "Fill in each field of the template when planning a new campaign. "
                "Minimum required fields: objective, target_segment, value_proposition, "
                "messaging_framework, channels. "
                "Optional but strongly recommended: insight_hook, cialdini_principles_to_activate."
            ),
        }

    async def get_objection_handlers(self, objection_type: str) -> list[dict]:
        """Get objection handling guidance based on Just Listen + Cialdini principles.

        Args:
            objection_type: One of: 'budget', 'timing', 'incumbent', 'authority',
                'trust', 'priority', or a free-form objection text.

        Returns:
            List of handling approach dicts with 'technique', 'example', 'principle'.
        """
        from packages.knowledge.src.frameworks import (  # noqa: PLC0415
            CIALDINI_PRINCIPLES,
            OBJECTION_HANDLING_FRAMEWORK,
            SINGAPORE_SME_CONTEXT,
        )

        objection_lower = objection_type.lower()
        sg_objections = SINGAPORE_SME_CONTEXT.get("common_objections", [])

        # Find matching Singapore-specific handling
        sg_handlers: list[dict] = []
        for obj_data in sg_objections:
            obj_text = obj_data.get("objection", "").lower()
            if any(word in objection_lower for word in obj_text.split()[:3]):
                sg_handlers.append({
                    "type": "singapore_specific",
                    "objection": obj_data.get("objection"),
                    "underlying_fear": obj_data.get("underlying_fear"),
                    "technique": obj_data.get("response_framework"),
                    "example": obj_data.get("sg_angle"),
                    "principle": "Goulston: acknowledge the fear, not just the words",
                })

        # Base handling from Goulston framework
        sequence = OBJECTION_HANDLING_FRAMEWORK.get("sequence", {})
        base_handlers = [
            {
                "type": "universal_sequence",
                "step": step_name,
                "technique": step_data.get("technique", ""),
                "description": step_data.get("description", ""),
                "principle": "Just Listen — Mark Goulston",
            }
            for step_name, step_data in sequence.items()
        ]

        # Add relevant Cialdini counter for budget/scarcity objections
        cialdini_handlers: list[dict] = []
        if any(w in objection_lower for w in ["budget", "cost", "price", "expensive"]):
            scarcity = CIALDINI_PRINCIPLES.get("scarcity", {})
            reciprocity = CIALDINI_PRINCIPLES.get("reciprocity", {})
            cialdini_handlers = [
                {
                    "type": "cialdini_counter",
                    "principle": "scarcity",
                    "technique": scarcity.get("application", ""),
                    "sg_example": scarcity.get("sg_angle", ""),
                },
                {
                    "type": "cialdini_counter",
                    "principle": "reciprocity",
                    "technique": reciprocity.get("application", ""),
                    "sg_example": reciprocity.get("sg_angle", ""),
                },
            ]
        elif any(w in objection_lower for w in ["trust", "credibility", "proven", "risk"]):
            authority = CIALDINI_PRINCIPLES.get("authority", {})
            social_proof = CIALDINI_PRINCIPLES.get("social_proof", {})
            cialdini_handlers = [
                {
                    "type": "cialdini_counter",
                    "principle": "authority",
                    "technique": authority.get("application", ""),
                    "sg_example": authority.get("sg_angle", ""),
                },
                {
                    "type": "cialdini_counter",
                    "principle": "social_proof",
                    "technique": social_proof.get("application", ""),
                    "sg_example": social_proof.get("sg_angle", ""),
                },
            ]

        return sg_handlers + base_handlers + cialdini_handlers

    async def get_singapore_context(self, topic: str | None = None) -> dict:
        """Return Singapore-specific GTM and SME market context.

        Args:
            topic: Optional topic filter, e.g. 'psg_grant', 'buying_triggers',
                'common_objections', 'channel_effectiveness'. If None, returns full context.

        Returns:
            Relevant Singapore SME context dict.
        """
        from packages.knowledge.src.frameworks import SINGAPORE_SME_CONTEXT  # noqa: PLC0415

        if topic is None:
            return SINGAPORE_SME_CONTEXT

        if topic in SINGAPORE_SME_CONTEXT:
            return {
                "topic": topic,
                "content": SINGAPORE_SME_CONTEXT[topic],
            }

        # Fuzzy match
        topic_lower = topic.lower()
        for key, value in SINGAPORE_SME_CONTEXT.items():
            if topic_lower in key.lower():
                return {"topic": key, "content": value}

        return {
            "topic": topic,
            "content": None,
            "available_topics": list(SINGAPORE_SME_CONTEXT.keys()),
        }

    async def get_sales_qualification_framework(self, deal_size: str = "mid") -> dict:
        """Return the appropriate sales qualification framework based on deal size.

        Args:
            deal_size: 'small' (< SGD 10k), 'mid' (SGD 10k–50k), 'enterprise' (> SGD 50k).

        Returns:
            The recommended qualification framework with rationale.
        """
        from packages.knowledge.src.frameworks import SALES_QUALIFICATION  # noqa: PLC0415

        size_lower = deal_size.lower()

        if any(w in size_lower for w in ["small", "low", "smb", "sme", "below"]):
            return {
                "deal_size": deal_size,
                "recommended": "BANT",
                "rationale": "BANT is sufficient for sub-SGD 10k deals — quick qualification, minimal process overhead.",
                "framework": SALES_QUALIFICATION.get("BANT", {}),
                "supplement_with": "SPIN for discovery questions",
            }
        elif any(w in size_lower for w in ["enterprise", "large", "complex", "above", "high"]):
            return {
                "deal_size": deal_size,
                "recommended": "MEDDIC",
                "rationale": "MEDDIC covers the full buying committee complexity of enterprise deals. BANT alone misses critical stakeholder dynamics.",
                "framework": SALES_QUALIFICATION.get("MEDDIC", {}),
                "supplement_with": "CHALLENGER for teaching and reframing",
            }
        else:  # mid
            return {
                "deal_size": deal_size,
                "recommended": "BANT + SPIN",
                "rationale": "Mid-market deals need BANT for fast qualification plus SPIN for thorough discovery to build implication and need-payoff.",
                "framework": {
                    "BANT": SALES_QUALIFICATION.get("BANT", {}),
                    "SPIN": SALES_QUALIFICATION.get("SPIN", {}),
                },
                "supplement_with": "STAR case studies to build credibility",
            }

    # ------------------------------------------------------------------
    # Layer 3: Semantic search over Qdrant
    # ------------------------------------------------------------------

    async def search_knowledge(
        self,
        query: str,
        agent_context: str | None = None,
        limit: int = 8,
    ) -> list[dict]:
        """Semantic search over all book chunks in the Qdrant marketing_knowledge collection.

        Falls back to returning relevant Layer 1 framework excerpts if Qdrant
        or OpenAI is not configured.

        Args:
            query: Natural language query, e.g. 'how to handle price objections in Singapore'.
            agent_context: Agent name (kebab-case) to filter results by relevance.
                If provided, results will be filtered to chunks tagged for this agent.
            limit: Maximum number of results to return.

        Returns:
            List of dicts with keys: book_title, chapter, page_number, text, score, agent_tags.
        """
        qdrant = await self._get_qdrant()
        openai_client = await self._get_openai()

        if qdrant is None or openai_client is None:
            logger.info(
                "Qdrant/OpenAI not configured — falling back to Layer 1 framework search for: %s",
                query,
            )
            return self._layer1_fallback_search(query, agent_context, limit)

        # Embed the query
        query_embedding = await self._embed_query(query, openai_client)
        if query_embedding is None:
            return self._layer1_fallback_search(query, agent_context, limit)

        try:
            from qdrant_client.models import FieldCondition, Filter, MatchAny  # noqa: PLC0415

            # Build optional agent filter
            search_filter = None
            if agent_context:
                agent_normalised = agent_context.replace("-", "_")
                search_filter = Filter(
                    must=[
                        FieldCondition(
                            key="agent_tags",
                            match=MatchAny(any=[agent_normalised]),
                        )
                    ]
                )

            response = await qdrant.query_points(
                collection_name="marketing_knowledge",
                query=query_embedding,
                query_filter=search_filter,
                limit=limit,
                with_payload=True,
            )

            results = []
            for hit in response.points:
                payload = hit.payload or {}
                results.append({
                    "book_title": payload.get("book_title", ""),
                    "book_key": payload.get("book_key", ""),
                    "chapter": payload.get("chapter"),
                    "page_number": payload.get("page_number", 0),
                    "text": payload.get("text", ""),
                    "score": round(hit.score, 4),
                    "agent_tags": payload.get("agent_tags", []),
                    "source": "qdrant_rag",
                })

            if not results:
                # Qdrant returned nothing — fall back to Layer 1
                return self._layer1_fallback_search(query, agent_context, limit)

            return results

        except Exception as exc:
            logger.warning("Qdrant search failed: %s — using Layer 1 fallback", exc)
            return self._layer1_fallback_search(query, agent_context, limit)

    # ------------------------------------------------------------------
    # Domain guides: synthesized knowledge from book chunks
    # ------------------------------------------------------------------

    async def get_domain_guide(self, slug: str) -> dict | None:
        """Load a synthesized domain guide from the guide store.

        Guides are JSON files generated by ``scripts/synthesize_domain_guides.py``,
        which retrieves Qdrant book chunks for a topic and uses GPT-4o to synthesize
        them into a structured operational guide.  When a guide file does not exist
        (because the synthesis script has not been run yet), this method returns
        ``None`` silently — agents should fall back to existing Layer 1 behaviour.

        Args:
            slug: Guide identifier, e.g. ``'digital_awareness_campaign'``,
                ``'cold_email_sequence'``, ``'icp_development'``.

        Returns:
            Guide dict with keys ``title``, ``source_books``, ``core_principles``,
            ``process_steps``, ``decision_rules``, ``singapore_adaptations``,
            ``common_mistakes``, ``success_metrics``, or ``None`` if not found.
        """
        # Guard against path traversal in slug.
        if "/" in slug or "\\" in slug or ".." in slug:
            return None
        # Prefer the _live.json variant (incrementally re-synthesized with
        # accumulated research) over the original static guide.
        live_path = _GUIDES_DIR / f"{slug}_live.json"
        base_path = _GUIDES_DIR / f"{slug}.json"
        guide_path = live_path if live_path.exists() else base_path
        if not guide_path.exists():
            logger.debug(
                "Domain guide '%s' not found — run scripts/synthesize_domain_guides.py", slug
            )
            return None
        try:
            return json.loads(guide_path.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.warning("Failed to load domain guide '%s': %s", slug, exc)
            return None

    async def list_available_guides(self) -> list[str]:
        """Return slugs of all synthesized guides currently in the guide store.

        Excludes ``_live.json`` variants — they are transparent alternates loaded
        by ``get_domain_guide()`` and should not be listed as separate entries.
        """
        if not _GUIDES_DIR.exists():
            return []
        return sorted(
            p.stem for p in _GUIDES_DIR.glob("*.json") if not p.stem.endswith("_live")
        )

    async def get_agent_knowledge_pack(
        self,
        agent_name: str,
        task_context: str = "",
        max_tokens: int = 800,
    ) -> dict:
        """Select and format the most relevant domain guides for an agent's task.

        Scores each candidate guide by keyword overlap with ``task_context``,
        loads the top 2 available guides, and returns a compact formatted injection
        block suitable for prepending to the agent's user message.

        Args:
            agent_name: Kebab-case agent name, e.g. ``'campaign-architect'``.
            task_context: Raw task string — used to select the most relevant guides
                by keyword overlap.  First 500 characters are used.
            max_tokens: Approximate token budget for the formatted injection block
                (1 token ≈ 4 characters).  Defaults to 800.

        Returns:
            Dict with keys:

            - ``'guides'``: list of loaded guide slugs.
            - ``'source_books'``: deduplicated list of source book titles.
            - ``'formatted_injection'``: ready-to-prepend expert knowledge block,
              empty string when no guides are available for this agent.
        """
        guide_slugs = _AGENT_GUIDE_MAP.get(agent_name, [])
        if not guide_slugs:
            return {"guides": [], "source_books": [], "formatted_injection": ""}

        task_lower = task_context[:500].lower()

        # Score each guide by keyword overlap with the task, preserving map order on ties.
        scored: list[tuple[int, int, str]] = []
        for idx, slug in enumerate(guide_slugs):
            keywords = _GUIDE_RELEVANCE_KEYWORDS.get(slug, slug.replace("_", " ").split())
            hits = sum(1 for kw in keywords if kw in task_lower)
            scored.append((hits, -idx, slug))
        scored.sort(reverse=True)

        # Try up to 4 candidates to load 2 available guides.
        loaded: list[dict] = []
        for _, _, slug in scored[:4]:
            if len(loaded) >= 2:
                break
            guide = await self.get_domain_guide(slug)
            if guide is not None:
                loaded.append(guide)

        if not loaded:
            return {"guides": [], "source_books": [], "formatted_injection": ""}

        # Deduplicate source books while preserving order.
        source_books: list[str] = list(
            dict.fromkeys(b for g in loaded for b in (g.get("source_books") or []))
        )
        return {
            "guides": [g["slug"] for g in loaded],
            "source_books": source_books,
            "formatted_injection": self._format_knowledge_pack(loaded, max_tokens=max_tokens),
        }

    async def synthesize_guide_incremental(
        self,
        slug: str,
        extra_texts: list[str] | None = None,
    ) -> bool:
        """Re-synthesize a guide using Qdrant book chunks + supplementary texts.

        Saves the result as ``{slug}_live.json`` — the original guide is never
        overwritten.  ``get_domain_guide()`` automatically prefers the live
        variant when it exists.

        Uses the already-initialised Qdrant and OpenAI clients (no external
        process, no file-lock conflict with the running gateway).

        Args:
            slug: Guide identifier, e.g. ``'cold_email_sequence'``.
            extra_texts: Optional list of supplementary research texts
                (e.g. accumulated ResearchCache content) to include alongside
                the book chunks in the synthesis prompt.

        Returns:
            ``True`` if a new ``{slug}_live.json`` was written, ``False`` on
            any failure (logged but never raised).
        """
        try:
            # Guard against path traversal in slug.
            if "/" in slug or "\\" in slug or ".." in slug:
                logger.warning("synthesize_guide_incremental: invalid slug '%s'", slug)
                return False

            # Load the existing guide to get search_queries and metadata.
            base_path = _GUIDES_DIR / f"{slug}.json"
            if not base_path.exists():
                logger.warning("synthesize_guide_incremental: base guide '%s' not found", slug)
                return False
            base_guide = json.loads(base_path.read_text(encoding="utf-8"))
            search_queries: list[str] = base_guide.get("search_queries", [])
            if not search_queries:
                # Derive from slug keywords as fallback.
                keywords = _GUIDE_RELEVANCE_KEYWORDS.get(slug, slug.replace("_", " ").split())
                search_queries = [" ".join(keywords)]

            title = base_guide.get("title", slug.replace("_", " ").title())
            agents_str = ", ".join(base_guide.get("agent_relevance", []))

            # Collect book chunks from Qdrant via embedding search.
            qdrant = await self._get_qdrant()
            openai = await self._get_openai()
            if qdrant is None or openai is None:
                logger.warning("synthesize_guide_incremental: Qdrant or OpenAI not available")
                return False

            seen_ids: set[str] = set()
            chunks: list[dict] = []
            for query in search_queries[:5]:
                try:
                    resp = await openai.embeddings.create(
                        model="text-embedding-3-small",
                        input=query.strip()[:6000],
                    )
                    embedding = resp.data[0].embedding
                    results = await qdrant.query_points(
                        collection_name="marketing_knowledge",
                        query=embedding,
                        limit=8,
                        with_payload=True,
                    )
                    for hit in results.points:
                        chunk_id = str(hit.id)
                        if chunk_id in seen_ids:
                            continue
                        seen_ids.add(chunk_id)
                        payload = hit.payload or {}
                        chunks.append({
                            "book_title": payload.get("book_title", "Unknown"),
                            "chapter": payload.get("chapter"),
                            "page_number": payload.get("page_number", 0),
                            "text": payload.get("text", ""),
                            "score": round(hit.score, 4),
                        })
                except Exception:
                    logger.debug("synthesize_guide_incremental: query failed", exc_info=True)

            chunks.sort(key=lambda c: c["score"], reverse=True)
            chunks = chunks[:20]

            if not chunks:
                logger.warning("synthesize_guide_incremental: no book chunks for '%s'", slug)
                return False

            # Build excerpts text (book chunks + extra research).
            book_titles = list(dict.fromkeys(c["book_title"] for c in chunks))
            excerpt_parts: list[str] = []
            for i, c in enumerate(chunks, 1):
                ch = f", {c['chapter']}" if c.get("chapter") else ""
                excerpt_parts.append(
                    f"[{i}] {c['book_title']}{ch} (p.{c['page_number']}, "
                    f"score={c['score']}):\n{c['text'][:800]}"
                )

            # Append supplementary research texts.
            extra = extra_texts or []
            for j, text in enumerate(extra[:10], len(chunks) + 1):
                excerpt_parts.append(
                    f"[{j}] RECENT MARKET RESEARCH (live data):\n{text[:800]}"
                )
            book_count = len(book_titles) + (1 if extra else 0)

            excerpts = "\n\n".join(excerpt_parts)
            must_cover = "\n".join(
                f"  - {item}" for item in base_guide.get("must_cover", [])
            ) or "  - Cover all key aspects of the topic"

            # Synthesis prompt — matches the format in synthesize_domain_guides.py
            # so incremental guides have consistent quality with initial ones.
            system_prompt = (
                "You are a marketing knowledge synthesizer. Your task is to extract "
                "structured, actionable operational guidance from real book excerpts "
                "— not from your general training knowledge.\n\n"
                "STRICT RULES:\n"
                "1. Every item in core_principles MUST cite its exact source book "
                "from the excerpts provided.\n"
                "2. Do NOT use knowledge not present in the provided excerpts — "
                'mark gaps as "(inferred — verify with source)".\n'
                "3. All text fields must be under 130 characters each "
                "(for token efficiency).\n"
                "4. decision_rules must follow strict IF/WHEN → action format.\n"
                "5. singapore_adaptations must be specific and practical, "
                "not generic.\n"
                "6. Return valid JSON ONLY — no markdown fences, no explanation "
                "text outside the JSON."
            )
            user_prompt = (
                f"GUIDE TOPIC: {title}\nAGENT USERS: {agents_str}\n"
                f"WHAT THIS GUIDE MUST COVER:\n{must_cover}\n\n"
                f"BOOK EXCERPTS ({len(chunks) + len(extra)} passages from "
                f"{book_count} sources):\n---\n{excerpts}\n---\n\n"
                "Synthesize ONLY from the excerpts above into this exact JSON "
                "structure:\n"
                "{\n"
                '  "core_principles": [\n'
                '    {"principle": "concise statement", "source": "exact book '
                'title", "application": "how to apply"}\n'
                "  ],\n"
                '  "process_steps": [\n'
                '    {"step": 1, "phase": "name", "objective": "goal", '
                '"actions": ["action1"], "timing": "Week 1-2"}\n'
                "  ],\n"
                '  "decision_rules": ["If [condition]: [action]"],\n'
                '  "singapore_adaptations": ["Specific SG adaptation"],\n'
                '  "common_mistakes": ["Specific mistake"],\n'
                '  "success_metrics": {"metric": "target value"}\n'
                "}\n\n"
                "REQUIREMENTS:\n"
                "- 3-5 core_principles, each citing a source book\n"
                "- 4-8 process_steps covering the end-to-end workflow\n"
                "- 5-8 decision_rules as IF/WHEN → action statements\n"
                "- 3-5 singapore_adaptations for Singapore B2B SME context\n"
                "- 3-5 common_mistakes (concrete, not vague)\n"
                "- 3-5 success_metrics with quantitative targets"
            )

            response = await openai.chat.completions.create(
                model="gpt-4o",
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.1,
                max_tokens=2000,
            )
            raw = response.choices[0].message.content or "{}"
            synthesized = json.loads(raw)

            # Validate that the synthesis produced meaningful content.
            # If the new guide has fewer core items than the base, the
            # Qdrant retrieval was incomplete — keep the original guide.
            required_keys = (
                "core_principles", "process_steps", "decision_rules",
                "singapore_adaptations", "common_mistakes",
            )
            for key in required_keys:
                if not isinstance(synthesized.get(key), list) or not synthesized[key]:
                    logger.warning(
                        "synthesize_guide_incremental_validation_failed slug=%s missing_key=%s",
                        slug,
                        key,
                    )
                    return False

            base_principles = len(base_guide.get("core_principles", []))
            new_principles = len(synthesized.get("core_principles", []))
            if base_principles > 0 and new_principles < base_principles * 0.6:
                logger.warning(
                    "synthesize_guide_incremental_content_loss slug=%s base=%d new=%d",
                    slug,
                    base_principles,
                    new_principles,
                )
                return False

            from datetime import UTC  # noqa: PLC0415
            from datetime import datetime as _dt

            guide = {
                **synthesized,
                "slug": slug,
                "title": title,
                "search_queries": search_queries,
                "agent_relevance": base_guide.get("agent_relevance", []),
                "source_books": book_titles,
                "source_chunk_count": len(chunks),
                "extra_research_count": len(extra),
                "synthesized_at": _dt.now(UTC).isoformat(),
                "synthesis_type": "incremental",
            }

            live_path = _GUIDES_DIR / f"{slug}_live.json"
            _GUIDES_DIR.mkdir(parents=True, exist_ok=True)
            # Atomic write: write to tmp file then os.replace() to avoid
            # corrupt _live.json if the process is killed mid-write.
            import os  # noqa: PLC0415

            tmp_path = live_path.with_suffix(".tmp")
            tmp_path.write_text(
                json.dumps(guide, indent=2, ensure_ascii=False), encoding="utf-8"
            )
            os.replace(tmp_path, live_path)
            logger.info(
                "guide_resynthesized slug=%s chunks=%d extra=%d",
                slug,
                len(chunks),
                len(extra),
            )
            return True

        except Exception:
            logger.warning("synthesize_guide_incremental_failed slug=%s", slug, exc_info=True)
            return False

    async def get_sg_reference(
        self,
        query: str,
        category_type: str | None = None,
        limit: int = 5,
    ) -> list[dict]:
        """Return relevant Singapore government reference data for a query.

        Searches the sg_knowledge_articles DB table. Falls back to the static
        PSG_STATIC_FALLBACK list from the scraper module when the DB is empty.

        Args:
            query: Free-text search query (matched against title + summary).
            category_type: Optional filter — "psg_vendor", "grant_overview",
                "enforcement", "regulation", "compliance", "market_data".
            limit: Maximum rows to return.

        Returns:
            List of dicts with keys: title, summary, url, source, category_type,
            last_verified.
        """
        try:
            from sqlalchemy import select  # noqa: PLC0415

            from packages.database.src.models import SgKnowledgeArticle  # noqa: PLC0415
            from packages.database.src.session import async_session_factory  # noqa: PLC0415

            async with async_session_factory() as db:
                stmt = select(SgKnowledgeArticle).where(SgKnowledgeArticle.is_active == True)  # noqa: E712
                if category_type:
                    stmt = stmt.where(SgKnowledgeArticle.category_type == category_type)
                stmt = stmt.order_by(SgKnowledgeArticle.fetched_at.desc()).limit(limit * 3)
                rows = list((await db.execute(stmt)).scalars().all())

            if not rows:
                # DB empty — return static fallback filtered by keyword
                return self._filter_static_sg(query, category_type, limit)

            # Simple keyword ranking against query terms
            query_terms = set(query.lower().split())
            scored: list[tuple[int, dict]] = []
            for row in rows:
                text = f"{row.title} {row.summary or ''}".lower()
                hits = sum(1 for t in query_terms if t in text)
                scored.append((hits, {
                    "title": row.title,
                    "summary": row.summary or "",
                    "url": row.url,
                    "source": row.source,
                    "category_type": row.category_type,
                    "last_verified": row.last_verified or row.fetched_at.date().isoformat(),
                }))
            scored.sort(key=lambda x: x[0], reverse=True)
            return [item for _, item in scored[:limit]]

        except Exception:
            logger.warning("get_sg_reference_failed", exc_info=True)
            return self._filter_static_sg(query, category_type, limit)

    def _filter_static_sg(
        self,
        query: str,
        category_type: str | None,
        limit: int,
    ) -> list[dict]:
        """Return keyword-scored items from the static PSG fallback list."""
        try:
            from packages.integrations.sg_reference.src.scraper import (
                PSG_STATIC_FALLBACK,  # noqa: PLC0415
            )
        except ImportError:
            return []
        query_terms = set(query.lower().split())
        results: list[tuple[int, dict]] = []
        for item in PSG_STATIC_FALLBACK:
            if category_type and item.get("category_type") != category_type:
                continue
            text = f"{item.get('title', '')} {item.get('summary', '')}".lower()
            hits = sum(1 for t in query_terms if t in text)
            results.append((hits, item))
        results.sort(key=lambda x: x[0], reverse=True)
        return [item for _, item in results[:limit]]

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    async def _get_openai(self):
        """Lazily initialise OpenAI client."""
        if self._openai_client is not None:
            return self._openai_client
        if not self._openai_api_key:
            return None
        try:
            import openai  # noqa: PLC0415

            self._openai_client = openai.AsyncOpenAI(api_key=self._openai_api_key)
            return self._openai_client
        except ImportError:
            return None

    async def _get_qdrant(self):
        """Lazily initialise Qdrant client."""
        if self._qdrant_client is not None:
            return self._qdrant_client
        url = self._qdrant_url
        path = self._qdrant_path
        if not url and not path:
            return None
        try:
            from qdrant_client import AsyncQdrantClient  # noqa: PLC0415

            if url:
                self._qdrant_client = AsyncQdrantClient(url=url)
            else:
                self._qdrant_client = AsyncQdrantClient(path=path)
            return self._qdrant_client
        except ImportError:
            return None

    async def _embed_query(self, query: str, client) -> list[float] | None:
        """Embed a single query string."""
        try:
            response = await client.embeddings.create(
                model="text-embedding-3-small",
                input=query.strip()[:6000],
            )
            return response.data[0].embedding
        except Exception as exc:
            logger.warning("Failed to embed query: %s", exc)
            return None

    def _layer1_fallback_search(
        self,
        query: str,
        _agent_context: str | None,
        limit: int,
    ) -> list[dict]:
        """Return relevant Layer 1 framework content as search results.

        When Qdrant is unavailable, we do lightweight keyword matching against
        the static framework constants to return the most relevant content.
        """
        import packages.knowledge.src.frameworks as fw  # noqa: PLC0415

        query_lower = query.lower()
        results: list[dict] = []

        # Keyword → framework mappings for fallback
        keyword_framework_map: list[tuple[list[str], str, object]] = [
            (
                ["cialdini", "persuasion", "reciprocity", "social proof", "scarcity", "authority", "liking"],
                "CIALDINI_PRINCIPLES",
                fw.CIALDINI_PRINCIPLES,
            ),
            (
                ["aida", "pas", "fab", "star", "bab", "messaging", "copywriting", "headline"],
                "MESSAGING_FRAMEWORKS",
                fw.MESSAGING_FRAMEWORKS,
            ),
            (
                ["ogilvy", "advertising", "copy", "headline principle"],
                "OGILVY_PRINCIPLES",
                fw.OGILVY_PRINCIPLES,
            ),
            (
                ["made to stick", "success", "simple", "unexpected", "concrete", "credible", "emotional", "stories"],
                "MADE_TO_STICK_SUCCESS",
                fw.MADE_TO_STICK_SUCCESS,
            ),
            (
                ["stp", "segmentation", "targeting", "positioning", "segment", "icp definition"],
                "STP_FRAMEWORK",
                fw.STP_FRAMEWORK,
            ),
            (
                ["gtm", "go-to-market", "product led", "sales led", "marketing led", "plg", "partner"],
                "GTM_FRAMEWORKS",
                fw.GTM_FRAMEWORKS,
            ),
            (
                ["bant", "meddic", "spin", "challenger", "qualification", "qualify", "sales process"],
                "SALES_QUALIFICATION",
                fw.SALES_QUALIFICATION,
            ),
            (
                ["icp", "ideal customer", "firmographic", "technographic", "behavioral", "psychographic"],
                "ICP_FRAMEWORK",
                fw.ICP_FRAMEWORK,
            ),
            (
                ["singapore", "psg", "enterprise sg", "entsg", "sme", "grant", "pdpa", "mas"],
                "SINGAPORE_SME_CONTEXT",
                fw.SINGAPORE_SME_CONTEXT,
            ),
            (
                ["objection", "handle", "pushback", "just listen", "goulston"],
                "OBJECTION_HANDLING_FRAMEWORK",
                fw.OBJECTION_HANDLING_FRAMEWORK,
            ),
            (
                ["race", "reach", "act", "convert", "engage", "digital marketing"],
                "RACE_FRAMEWORK",
                fw.RACE_FRAMEWORK,
            ),
            (
                ["4p", "product", "price", "place", "promotion", "marketing mix"],
                "MARKETING_MIX_4P",
                fw.MARKETING_MIX_4P,
            ),
            (
                ["porter", "five forces", "competitive", "rivalry", "entrant", "substitute", "buyer power"],
                "PORTER_FIVE_FORCES",
                fw.PORTER_FIVE_FORCES,
            ),
        ]

        for keywords, framework_name, framework_content in keyword_framework_map:
            if any(kw in query_lower for kw in keywords):
                # Summarise the content to avoid massive dicts in results
                content_summary = self._summarise_framework(framework_content, framework_name)
                results.append({
                    "book_title": f"Static Knowledge: {framework_name}",
                    "book_key": "frameworks_py",
                    "chapter": None,
                    "page_number": 0,
                    "text": content_summary,
                    "score": 0.9,  # high relevance from keyword match
                    "agent_tags": [],
                    "source": "layer1_static",
                    "framework_name": framework_name,
                })
                if len(results) >= limit:
                    break

        return results[:limit]

    def _format_knowledge_pack(self, guides: list[dict], max_tokens: int = 800) -> str:
        """Format loaded guides into a compact injection block within the token budget.

        Budget is split evenly across guides.  1 token ≈ 4 characters.
        """
        char_budget = max_tokens * 4
        per_guide = char_budget // max(len(guides), 1)
        sections = [self._format_single_guide(g, char_limit=per_guide) for g in guides]
        return "\n\n".join(sections)

    def _format_single_guide(self, guide: dict, char_limit: int = 1600) -> str:
        """Render one guide as a compact, token-efficient plain-text block.

        Uses bullet points and short labels so the LLM parses it naturally.
        Truncates on a line boundary if the content exceeds ``char_limit`` characters.
        """
        lines: list[str] = []

        title = guide.get("title", guide.get("slug", "Expert Knowledge"))
        books = "; ".join(guide.get("source_books", [])[:3])
        lines.append(f"=== SYNTHESISED KNOWLEDGE: {title} ===")
        if books:
            lines.append(f"Source: {books}")

        principles = guide.get("core_principles", [])
        if principles:
            lines.append("\nCORE PRINCIPLES:")
            for p in principles[:3]:
                principle = p.get("principle", "")
                source = p.get("source", "")
                src_note = f" ({source})" if source else ""
                lines.append(f"• {principle}{src_note}")

        steps = guide.get("process_steps", [])
        if steps:
            lines.append("\nHOW TO EXECUTE:")
            for s in steps[:5]:
                phase = s.get("phase", f"Step {s.get('step', '')}")
                timing = s.get("timing", "")
                timing_note = f" [{timing}]" if timing else ""
                actions = s.get("actions", [])
                action_str = "; ".join(actions[:2]) if actions else s.get("objective", "")
                lines.append(f"{s.get('step', '•')}. {phase}{timing_note}: {action_str}")

        rules = guide.get("decision_rules", [])
        if rules:
            lines.append("\nDECISION RULES:")
            for r in rules[:4]:
                lines.append(f"• {r}")

        sg = guide.get("singapore_adaptations", [])
        if sg:
            lines.append("\nSINGAPORE:")
            for item in sg[:3]:
                lines.append(f"• {item}")

        mistakes = guide.get("common_mistakes", [])
        if mistakes:
            lines.append("\nAVOID:")
            for m in mistakes[:3]:
                lines.append(f"• {m}")

        metrics = guide.get("success_metrics", {})
        if metrics:
            metric_str = " | ".join(f"{k}: {v}" for k, v in list(metrics.items())[:3])
            lines.append(f"\nBENCHMARKS: {metric_str}")

        full = "\n".join(lines)
        if len(full) <= char_limit:
            return full

        # Truncate on a line boundary.
        truncated = full[:char_limit]
        last_newline = truncated.rfind("\n")
        if last_newline >= 0:
            truncated = truncated[:last_newline]
        return truncated + "\n[truncated to fit token budget]"

    def _summarise_framework(self, content: object, name: str) -> str:
        """Create a concise text summary of a framework for search results."""
        if isinstance(content, dict):
            # Take first 3 keys and their descriptions
            lines = [f"Framework: {name}"]
            for i, (k, v) in enumerate(content.items()):
                if i >= 3:
                    break
                if isinstance(v, dict):
                    desc = v.get("description", str(v)[:200])
                elif isinstance(v, str):
                    desc = v[:200]
                else:
                    desc = str(v)[:200]
                lines.append(f"  {k}: {desc}")
            return "\n".join(lines)
        elif isinstance(content, list):
            lines = [f"Framework: {name} — {len(content)} principles"]
            for i, item in enumerate(content[:3]):
                if isinstance(item, dict):
                    principle = item.get("principle", item.get("name", f"Item {i + 1}"))
                    desc = item.get("description", "")[:150]
                    lines.append(f"  {i + 1}. {principle}: {desc}")
                else:
                    lines.append(f"  {i + 1}. {str(item)[:150]}")
            return "\n".join(lines)
        else:
            return f"Framework: {name}\n{str(content)[:400]}"


@lru_cache(maxsize=1)
def get_knowledge_mcp() -> KnowledgeMCPServer:
    """Return the process-wide singleton KnowledgeMCPServer."""
    return KnowledgeMCPServer()


def get_guide_relevance_keywords() -> dict[str, list[str]]:
    """Return a copy of the guide-slug → relevance-keywords mapping.

    Public accessor so that cross-package callers (e.g. scheduler) do not
    need to import the private ``_GUIDE_RELEVANCE_KEYWORDS`` dict directly.
    """
    return dict(_GUIDE_RELEVANCE_KEYWORDS)
