"""Database package for GTM Advisor."""

from .knowledge_web import (
    CompetitorSignalRepository,
    EntityRelationRepository,
    EntityRepository,
    EvidencedFactRepository,
    KnowledgeWebService,
    LeadJustificationRepository,
    MCPDataSourceRepository,
)
from .models import (
    ICP,
    Analysis,
    AnalysisStatus,
    AuditLog,
    Base,
    Campaign,
    CampaignStatus,
    Company,
    Competitor,
    CompetitorAlert,
    CompetitorSignal,
    Consent,
    ConsentPurpose,
    Entity,
    EntityRelation,
    # Knowledge Web Models
    EntityType,
    EvidencedFact,
    FactEntityLink,
    FactRelationLink,
    FactType,
    Lead,
    LeadJustification,
    LeadStatus,
    MarketInsight,
    MCPDataSource,
    Persona,
    RelationType,
    SourceType,
    # Enums
    SubscriptionTier,
    ThreatLevel,
    User,
)
from .session import AsyncSessionLocal, close_db, get_db, get_db_session, init_db

__all__ = [
    # Models
    "Base",
    "User",
    "Company",
    "Analysis",
    "Consent",
    "AuditLog",
    "Competitor",
    "CompetitorAlert",
    "ICP",
    "Persona",
    "Lead",
    "Campaign",
    "MarketInsight",
    # Knowledge Web Models
    "EvidencedFact",
    "Entity",
    "EntityRelation",
    "FactEntityLink",
    "FactRelationLink",
    "LeadJustification",
    "CompetitorSignal",
    "MCPDataSource",
    # Enums
    "SubscriptionTier",
    "AnalysisStatus",
    "ConsentPurpose",
    "ThreatLevel",
    "LeadStatus",
    "CampaignStatus",
    "SourceType",
    "FactType",
    "EntityType",
    "RelationType",
    # Knowledge Web Repositories
    "EvidencedFactRepository",
    "EntityRepository",
    "EntityRelationRepository",
    "LeadJustificationRepository",
    "CompetitorSignalRepository",
    "MCPDataSourceRepository",
    "KnowledgeWebService",
    # Session
    "get_db",
    "get_db_session",
    "init_db",
    "close_db",
    "AsyncSessionLocal",
]
