"""Database package for Kairos."""

from .knowledge_web import (
    CompetitorSignalRepository,
    EntityRelationRepository,
    EntityRepository,
    EvidencedFactRepository,
    KnowledgeWebService,
    LeadJustificationRepository,
    MCPDataSourceRepository,
)
from .models import (
    ICP,
    Analysis,
    AnalysisStatus,
    AuditLog,
    Base,
    Campaign,
    CampaignStatus,
    Company,
    CompanyDocument,
    CompanyExecutive,
    CompanyFinancialSnapshot,
    CompanyListingType,
    Competitor,
    CompetitorAlert,
    CompetitorSignal,
    Consent,
    ConsentPurpose,
    DocumentChunk,
    DocumentType,
    Entity,
    EntityRelation,
    # Knowledge Web Models
    EntityType,
    EvidencedFact,
    FactEntityLink,
    FactRelationLink,
    FactType,
    FinancialPeriodType,
    GTMRoadmap,
    Lead,
    LeadJustification,
    LeadStatus,
    ListedCompany,
    MarketArticle,
    MarketInsight,
    MarketVertical,
    MCPDataSource,
    Persona,
    RelationType,
    RoadmapPhase,
    RoadmapStatus,
    SourceType,
    # Enums
    SubscriptionTier,
    ThreatLevel,
    User,
    VerticalBenchmark,
)
from .repositories import (
    AnalysisRepository,
    AuditRepository,
    LeadRepository,
    MarketInsightRepository,
)
from .session import AsyncSessionLocal, close_db, get_db, get_db_session, init_db

__all__ = [
    # Models
    "Base",
    "User",
    "Company",
    "Analysis",
    "Consent",
    "AuditLog",
    "Competitor",
    "CompetitorAlert",
    "ICP",
    "Persona",
    "Lead",
    "Campaign",
    "MarketInsight",
    # Knowledge Web Models
    "EvidencedFact",
    "Entity",
    "EntityRelation",
    "FactEntityLink",
    "FactRelationLink",
    "LeadJustification",
    "CompetitorSignal",
    "MCPDataSource",
    # Market Intelligence Models
    "MarketVertical",
    "ListedCompany",
    "CompanyFinancialSnapshot",
    "VerticalBenchmark",
    "MarketArticle",
    "CompanyDocument",
    "DocumentChunk",
    "CompanyExecutive",
    # GTM Roadmap Models
    "GTMRoadmap",
    # Enums
    "AnalysisStatus",
    "CampaignStatus",
    "CompanyListingType",
    "ConsentPurpose",
    "DocumentType",
    "EntityType",
    "FactType",
    "FinancialPeriodType",
    "LeadStatus",
    "RelationType",
    "RoadmapPhase",
    "RoadmapStatus",
    "SourceType",
    "SubscriptionTier",
    "ThreatLevel",
    # GTM Repositories
    "AnalysisRepository",
    "LeadRepository",
    "MarketInsightRepository",
    "AuditRepository",
    # Knowledge Web Repositories
    "EvidencedFactRepository",
    "EntityRepository",
    "EntityRelationRepository",
    "LeadJustificationRepository",
    "CompetitorSignalRepository",
    "MCPDataSourceRepository",
    "KnowledgeWebService",
    # Session
    "get_db",
    "get_db_session",
    "init_db",
    "close_db",
    "AsyncSessionLocal",
]
